### ISSUE TITLE
GBIF cached images are different from images at the source

### ISSUE THREAD

**Issue by matdillen** [bio-guoda/preston#111]
GBIF keeps a cache of the images referenced by data providers. This is done through [thumbor](http://thumbor.org/). These cached images differ from the original ones at the referenced source. There may be differences in file metadata, such as changes in print resolution and loss of some metadata, but also the JPEG quality itself.

Thumbor reproduces a cached image with certain requested parameters. If none are specified, the app will use some defaults and create an image accordingly. I don't think it's possible to recreate an identical JPEG image with this process, given the lossy nature of JPEG decompression. So we will need access to the original files, if that is possible? 

Examples:

Slight difference:
[Occurrence record](https://www.gbif.org/occurrence/2595657020)
[Original image source](http://oxalis.br.fgov.be/images/V/BR0/000/025/856/880/BR0000025856880V.jpg)
[GBIF cached image](https://api.gbif.org/v1/image/unsafe/http%3A%2F%2Foxalis.br.fgov.be%2Fimages%2FV%2FBR0%2F000%2F025%2F856%2F880%2FBR0000025856880V.jpg)

Big difference:
[Occurrence record](https://www.gbif.org/occurrence/465102905)
[Original image source](http://mediaphoto.mnhn.fr/media/1441319501228J9DUIyjSgi6vMFSN)
[GBIF cached image](https://api.gbif.org/v1/image/unsafe/http%3A%2F%2Fmediaphoto.mnhn.fr%2Fmedia%2F1441319501228J9DUIyjSgi6vMFSN)

**Comment by jhpoelen** [comment]
@matdillen thanks for sharing your detailed comparison between original and cached images related to records registered in the GBIF network. 

Given that content served via URLs is known the change or disappear, I've just sampled the sha256 hash of the images as well as cloned images from their current locations using: 

```
$ preston track https://api.gbif.org/v1/occurrence/2595657020 https://api.gbif.org/v1/occurrence/465102905 https://api.gbif.org/v1/image/unsafe/http%3A%2F%2Fmediaphoto.mnhn.fr%2Fmedia%2F1441319501228J9DUIyjSgi6vMFSN https://api.gbif.org/v1/image/unsafe/http%3A%2F%2Foxalis.br.fgov.be%2Fimages%2FV%2FBR0%2F000%2F025%2F856%2F880%2FBR0000025856880V.jpg | grep hasVersion
<https://api.gbif.org/v1/occurrence/2595657020> <http://purl.org/pav/hasVersion> <hash://sha256/91b826d93a920b243399f05214b3a9cbb2b3b1e231b8e6ebe774f24508e6e41e> <urn:uuid:fcb1eed6-e840-4297-818b-98fe7ccdebe6> .
<http://oxalis.br.fgov.be/images/V/BR0/000/025/856/880/BR0000025856880V.jpg> <http://purl.org/pav/hasVersion> <hash://sha256/3e4506c89b1f16e95604adbc9a49d47be75095e0e45aaf526de5f8a6fb33caad> <urn:uuid:e1d33c6f-7dea-4787-ba48-9e4a064f72c7> .
<https://www.gbif.org/occurrence/465102905> <http://purl.org/pav/hasVersion> <hash://sha256/0916df73b87a58beca95e8c5db0aafdcbcb8fef61cf521cf7f09c76f706aed6d> <urn:uuid:4e4e1304-815a-48ec-a56f-26ed103fb487> .
<https://api.gbif.org/v1/occurrence/465102905> <http://purl.org/pav/hasVersion> <hash://sha256/ec46d68ab36e752495764efd5451b19ac51d57992851bb89c858c57296c9a028> <urn:uuid:ab90d3ae-2d97-44c6-9773-e8c6caad21af> .
<http://mediaphoto.mnhn.fr/media/1441319501228J9DUIyjSgi6vMFSN> <http://purl.org/pav/hasVersion> <hash://sha256/0e9f12531e5371ec0b3c2b28cb2f0ae47e8c8420941f3770a85e63756a75d84d> <urn:uuid:222547d1-5f7b-458a-ad95-21344f0c2bf1> .
<https://api.gbif.org/v1/image/unsafe/http%3A%2F%2Fmediaphoto.mnhn.fr%2Fmedia%2F1441319501228J9DUIyjSgi6vMFSN> <http://purl.org/pav/hasVersion> <hash://sha256/5bf7b372806c606efb5541b735dac4023c417b77d853361d9e9df09be2743c3b> <urn:uuid:3cd977a6-1ba0-4c41-a3e6-1e6ce6f2f124> .
<https://api.gbif.org/v1/image/unsafe/http%3A%2F%2Foxalis.br.fgov.be%2Fimages%2FV%2FBR0%2F000%2F025%2F856%2F880%2FBR0000025856880V.jpg> <http://purl.org/pav/hasVersion> <hash://sha256/73a7cd67564da391204ba2e0a17795913015a0d2e079c4d3cd5125ed0e37c610> <urn:uuid:45e0d2f6-7249-44bd-ae61-4231ba018fbb> .
```

I've attached the related content using convention [sha256].jpg . Like you described, the hash of the source and cached images are different, suggesting that some transformation of the original image occurred. 

 source |  cached | 
 --- | ---
hash://sha256/3e45... ![3e4506c89b1f16e95604adbc9a49d47be75095e0e45aaf526de5f8a6fb33caad](https://user-images.githubusercontent.com/1084872/110965234-d9ae7c00-8308-11eb-8454-44498be27beb.jpg) | hash://sha256/73a7...  ![73a7cd67564da391204ba2e0a17795913015a0d2e079c4d3cd5125ed0e37c610](https://user-images.githubusercontent.com/1084872/110965140-c4d1e880-8308-11eb-9356-e085dd6112c8.jpg)
hash://sha256/0e9f... ![0e9f12531e5371ec0b3c2b28cb2f0ae47e8c8420941f3770a85e63756a75d84d](https://user-images.githubusercontent.com/1084872/110965274-e206b700-8308-11eb-9349-44cddbb6218e.jpg) | hash://sha256/5bf7... ![5bf7b372806c606efb5541b735dac4023c417b77d853361d9e9df09be2743c3b](https://user-images.githubusercontent.com/1084872/110965183-cdc2ba00-8308-11eb-9c2b-4dc63f31e818.jpg)

I am not quite sure how gbif processes these images, perhaps others might know.

**Comment by jhpoelen** [comment]
@mdoering @MattBlisset - an earlier comment by @matdillen indicate that the provenance of GBIF image caches is unclear. If I understand correctly, GBIF keeps an image cache to improve the user experience on gbif.org . It appears that _altered_ copies of the original images are used on the site, and no clear path to unaltered copies is available. Please comment if you'd like to share some more on the background and process of image caching in GBIF infrastructure.

**Comment by matdillen** [comment]
> 
> 
> > and no clear path to unaltered copies is available.
> 
> @jhpoelen I would go looking into the multimedia extension file of the DwC archive for the original image identifiers, and fetch them directly from the providing image store. But I might be misunderstanding your comment?

I think the problem with this is that you'd have to make another request to another server. That request may fail (if the image there has moved or the server has problems) or may be slow and time out. And it increases the overhead of compiling images.

**Comment by jhpoelen** [comment]
The point I am trying to make is that if the provenance of the images are retained as along with the reliably referenced image copies, the corpus can be cloned without have to go back to the original source. Similar to what happens when cloning git repositories. 

So, for GBIF image cache, you could make explicit the image transformations:

original image -(thumbor with settings X)-> derived image A (e.g., thumbnail)
original image -(thumbor with settings Y)-> derived image B (e.g., medium size)
original image -(thumbor with settings Z)-> derived image C (e.g., full size)

where the original image is referred to by its content identifiers (e.g., hash, fixity) rather that the location it happened to be located at some point.

then, on cloning the corpus, you'd include the provenance above as well as the associated images to make sure the image corpus is complete.

**Comment by jhpoelen** [comment]
Closing stale discussion on how to document the processing of original images by GBIF's image cache.
