### ISSUE TITLE
wrong order of operations in bloom filter identifiers?

### ISSUE THREAD

**Issue by mielliott** [bio-guoda/preston#131]
Running `preston bloom` saves bloom filters for input datasets and are identified as e.g.
```
bloom:gz:hash://abc...
```
which I believe implies that the "gz" operation (compressing the data) was performed first, then the "bloom" (building the filter), but looking at the code,
https://github.com/bio-guoda/preston/blob/f24058fac44c9391577cfd44018c111212819061/preston-cli/src/main/java/bio/guoda/preston/process/SketchBuilderBloomFilter.java#L86-L89
it looks like the compression occurs after computing the bloom filter (also, it wouldn't make sense to use a bloom filter on compressed data). Suggest to change the prefix from
```
bloom:gz
```
to
```
gz:bloom
```

@jhpoelen I'm happy to make this change if you agree

**Comment by jhpoelen** [comment]
@mielliott nice catch! I agree that ```gz:bloom``` makes more sense and consistent with the implementation. Would be great if you could make the change, happy to review if needed.

**Comment by mielliott** [comment]
Thanks for confirming. It's fixed, gonna go ahead and close this
