### ISSUE TITLE
Share and cite 3D images from Big-Bee project

### ISSUE THREAD

**Issue by seltmann** [bio-guoda/preston#146]
Using image stacks and .obj files to build 3D models of a bee specimen. Would like to share, reference and cite these together as a packaged publication. Also, we would like to find ways to archive these publications on Zenodo. This 3D model was built with Agisoft Metashape.

An example .obj file https://ucsb.box.com/s/ic3ivu01v0u6k9p8gjrg3la0av80g5n2 can be found here.

This .obj file links together these images https://ucsb.box.com/s/pukvkv4jvn3jc5m93bladf3w3kjzr6kn

All of the files for this specimen are found here: https://ucsb.box.com/s/of6cdxpoom1vi9s37tjbtlhk3xx46uxu

![Screen Shot 2022-01-14 at 2 19 29 PM](https://user-images.githubusercontent.com/1044474/149592638-c8f9e47c-24a2-4f89-9978-911eec790c23.png)

**Comment by seltmann** [comment]
The product would be separate Zenodo publications, acting like websites and similar to https://jhpoelen.nl/bees/16f6de61-541c-46b1-b7e7-d8303e6f53db

**Comment by jhpoelen** [comment]
related see https://github.com/bio-guoda/preston/issues/148#issuecomment-1063419783 .

**Comment by jhpoelen** [comment]
See notes of Digital Data 2022 of 3D model Symposium on https://docs.google.com/document/d/1EI4H0DbnZuBOc9ekg_aXvzhzlV92Z7l8VqK6QcD_UG8/edit# for inspiration.

**Comment by jhpoelen** [comment]
Nicole Gunter shared their 3d imagesets via Zoom chat: https://specimens.mantodearesearch.com/360/imagelist Here are all our rotations so far, click on the blue specimen names and it will take you to specific rotations at the Entomology Collections Management workshop 22 June 2022 .

**Comment by jhpoelen** [comment]
@seltmann do you know anyone using Pixar's USD https://en.wikipedia.org/wiki/Universal_Scene_Description to package 3D models?

**Comment by seltmann** [comment]
Example:
3d model of Xylocopa varipuncta, UCSB IZC collection, catalog number: UCSB-IZC00012194

In multimedia.csv file "comments" state: _Image used to create 3D photogrammetry model_
AND image file name contains **_3d_**

Images ordered in time based on a time stamp found in filename. For example, in the file:
https://serv.biokic.asu.edu/imglib/ecdysis/UCSB_IZC/UCSB-IZC00012/UCSB-IZC00012194_3d_2020-08-08-08.12.56.jpg, 2020-08-08-08.12.56 is the timestamp with date.

Archive from bee library published at https://library.big-bee.net/portal/content/dwca/UCSB-IZC_DwC-A.zip

Models created with Agisoft Metashape (need REadme from Katja). TODO how are you keeping track of images that go into a specific model. Maybe a table that incorperates into the model folder. MR version and HR version.

https://drive.google.com/file/d/1HbSqyUvYtz43Lx403pKZ2q8c0Lf2d6dH/view?usp=sharing

**Comment by jhpoelen** [comment]
example of qrcode with text - @seltmann 

![label-with-text](https://user-images.githubusercontent.com/1084872/192059611-14b812d7-c971-43dc-973e-dd87cc2fb717.png)

**Comment by jhpoelen** [comment]
can be decoded using programs like those published on -

https://zxing.org/w/decode.jspx

**Comment by jhpoelen** [comment]
@seltmann for prototype, see https://github.com/Big-Bee-Network/3bee.gif .

![bee](https://github.com/Big-Bee-Network/3bee.gif/raw/main/bee.gif)
