### ISSUE TITLE
support Zenodo compatible per-specimen publication 

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/preston#147]
as discussed with @seltmann 

workflow idea:

1. select specimen
2. let preston create a Zenodo ready publication (meta-data + files)
3. publish on Zenodo after manual review / curation

**Comment by seltmann** [comment]
The product would be separate Zenodo publications for each specimen, acting like websites and similar to https://jhpoelen.nl/bees/16f6de61-541c-46b1-b7e7-d8303e6f53db

**Comment by jhpoelen** [comment]
related see https://github.com/bio-guoda/preston/issues/148#issuecomment-1063419783

**Comment by jhpoelen** [comment]
See more specific example created by @seltmann #157
