### ISSUE TITLE
Add functionality to reprocess provenance logs

### ISSUE THREAD

**Issue by mielliott** [bio-guoda/preston#15]
Suggest to add functionality to insert the missing relationships from #14 to existing provenance logs by piping them back into Preston for reprocessing.

```shell
$ preston ls | preston replay > prov_log_updated
```

**Comment by jhpoelen** [comment]
@mielliott I took a first pass at functionality for re-processing provenance logs and introduced: ```preston process``` . 

The idea is to use stdin to feed existing provenance logs (whole or in part) into preston. Preston then takes processes each and every statement with it's content processors, and generated the original + new (if any) content and adds it as a new provenance log version.

For instance, to reprocess all existing logs, you can do:

```preston ls | preston process```

to include do a single line, you can do:

```shell
$ preston ls | grep gfbio | preston process
<https://preston.guoda.bio> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <h
ttp://www.w3.org/ns/prov#SoftwareAgent> .
<https://preston.guoda.bio> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <h
ttp://www.w3.org/ns/prov#Agent> .
<https://preston.guoda.bio> <http://purl.org/dc/terms/description> "Preston is a
 software program that finds, archives and provides access to biodiversity datas
ets."@en .
<9a226967-1b33-4524-98c0-fcf5787a267d> <http://www.w3.org/1999/02/22-rdf-syntax-
ns#type> <http://www.w3.org/ns/prov#Activity> .
<9a226967-1b33-4524-98c0-fcf5787a267d> <http://purl.org/dc/terms/description> "A
n event that (re-) processes existing biodiversity datasets graphs and their pro
venance."@en .
<9a226967-1b33-4524-98c0-fcf5787a267d> <http://www.w3.org/ns/prov#startedAtTime>
 "2019-07-14T01:14:49.151Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
<9a226967-1b33-4524-98c0-fcf5787a267d> <http://www.w3.org/ns/prov#wasStartedBy> 
<https://preston.guoda.bio> .
<0659a54f-b713-4f86-a917-5be166a14110> <http://www.w3.org/1999/02/22-rdf-syntax-
ns#type> <http://www.w3.org/ns/prov#Entity> .
<0659a54f-b713-4f86-a917-5be166a14110> <http://purl.org/dc/terms/description> "A
 biodiversity dataset graph archive."@en .
<hash://sha256/4ae6725e255e58639a9f3ea15fe06ba015bfb25be5526fd803e6266266e4ba52>
 <http://www.w3.org/ns/prov#usedBy> <9a226967-1b33-4524-98c0-fcf5787a267d> .
<https://bms.gfbio.org/services/data-sources/> <http://purl.org/pav/hasVersion> <hash://sha256/c512d491c472bc004ecdf5a0f30e226bc20bbaed1bdc05a9a08f973f19e18878>
 .
<hash://sha256/c512d491c472bc004ecdf5a0f30e226bc20bbaed1bdc05a9a08f973f19e18878>
 <http://www.w3.org/ns/prov#hadMember> <https://ww3.bgbm.org/biocase/pywrapper.c
gi?dsa=GFBio_ColiFauna&inventory=1> .
<https://ww3.bgbm.org/biocase/pywrapper.cgi?dsa=GFBio_ColiFauna&inventory=1> <ht
tp://purl.org/dc/elements/1.1/format> "text/xml" .
<hash://sha256/c512d491c472bc004ecdf5a0f30e226bc20bbaed1bdc05a9a08f973f19e18878>
 <http://www.w3.org/ns/prov#hadMember> <https://ww3.bgbm.org/biocase/pywrapper.c
gi?dsa=GFBio_eXist-db&inventory=1> .
<https://ww3.bgbm.org/biocase/pywrapper.cgi?dsa=GFBio_eXist-db&inventory=1> <htt
p://purl.org/dc/elements/1.1/format> "text/xml" .
<hash://sha256/c512d491c472bc004ecdf5a0f30e226bc20bbaed1bdc05a9a08f973f19e18878>
 <http://www.w3.org/ns/prov#hadMember> <https://ww3.bgbm.org/biocase/pywrapper.c
gi?dsa=GFBio_eXist-db&inventory=1> .
``` 

Note that only a pre-existing version of the bioCASe registry was needed (e.g., ```<https://bms.gfbio.org/services/data-sources/> <http://purl.org/pav/hasVersion <hash://sha256/c512....> .```) to generate the ```http://www.w3.org/ns/prov#hadMember``` relationships.

This is even more emphasized when running:

```shell
$ echo -e "<https://bms.gfbio.org/services/data-sources/> <http://purl.org/pav/hasVersion> <hash://sha256/c512d491c472bc004ecdf5a0f30e226bc20bbaed1bdc05a9a08f973f19e18878> .\n" | preston process
...
<https://bms.gfbio.org/services/data-sources/> <http://purl.org/pav/hasVersion> <hash://sha256/c512d491c472bc004ecdf5a0f30e226bc20bbaed1bdc05a9a08f973f19e18878> .
 <http://www.w3.org/ns/prov#hadMember> <https://ww3.bgbm.org/biocase/pywrapper.c
gi?dsa=GFBio_ColiFauna&inventory=1> .
<https://ww3.bgbm.org/biocase/pywrapper.cgi?dsa=GFBio_ColiFauna&inventory=1> <ht
tp://purl.org/dc/elements/1.1/format> "text/xml" .
<hash://sha256/c512d491c472bc004ecdf5a0f30e226bc20bbaed1bdc05a9a08f973f19e18878>
 <http://www.w3.org/ns/prov#hadMember> <https://ww3.bgbm.org/biocase/pywrapper.c
gi?dsa=GFBio_eXist-db&inventory=1> .
<https://ww3.bgbm.org/biocase/pywrapper.cgi?dsa=GFBio_eXist-db&inventory=1> <htt
p://purl.org/dc/elements/1.1/format> "text/xml" .
<hash://sha256/c512d491c472bc004ecdf5a0f30e226bc20bbaed1bdc05a9a08f973f19e18878>
 <http://www.w3.org/ns/prov#hadMember> <https://ww3.bgbm.org/biocase/pywrapper.c
gi?dsa=GFBio_eXist-db&inventory=1> .
<https://ww3.bgbm.org/biocase/pywrapper.cgi?dsa=GFBio_eXist-db&inventory=1> <htt
p://purl.org/dc/elements/1.1/format> "text/xml" .
```

So, with this, you can add the hadMember relationship for bioCASe (#14) for older provenance logs using:
```shell
$ preston ls | grep "pywrapper.cgi?dsa" | grep hasVersion | preston process
```
for the individual datasets (e.g., <data hash> hadMember <dwca url> and <dataset hash> hadMember <abcda url>).

For creating hadMembership relations for bioCASe registry something like:

```shell
$ preston ls | grep  "https://bms.gfbio.org/services/data-sources/" | grep "hasVersion" | preston process
```

Note that piping all of the provenance logs into preston will probably result is a giant single log with old and added statements. These logs might be > 1GB . 

Also note that if we decide to go for this and patch the existing bioCASe provenance logs in the preston observatory in Germany, we'd have to run it there first, then sync. If you run it locally, you'll effectively fork your provenance log version history and won't see the newly added content from Germany.

**Comment by jhpoelen** [comment]
Curious to hear you comments if you have any.

**Comment by jhpoelen** [comment]
Functionality is included in https://github.com/bio-guoda/preston/releases/tag/0.1.2 . 

Am now running tests for patching bioCASe provenance logs with:

```preston ls --remote https://deeplinker.bio | grep "pywrapper?dsa" | grep "hasVersion" | preston process --remote https://deeplinker.bio```

**Comment by jhpoelen** [comment]
See attached for results of:
1. biocase registry members via ```preston ls --remote https://deeplinker.bio | grep -e "https://bms.gfbio.org/services/data-sources/" | preston process --remote https://deeplinker.bio``` 
[biocase_dataset_members.nq.gz](https://github.com/bio-guoda/preston/files/3389482/biocase_dataset_members.nq.gz)


2. biocase dataset members via ```preston ls --remote https://deeplinker.bio | grep "pywrapper.cgi?dsa" | grep "hasVersion" | preston process --remote https://deeplinker.bio``` 
[biocase_dataset_members.nq.gz](https://github.com/bio-guoda/preston/files/3389481/biocase_dataset_members.nq.gz)

**Comment by mielliott** [comment]
Functionality has been added, closing.
