### ISSUE TITLE
Change default behavior for `preston origins`

### ISSUE THREAD

**Issue by mielliott** [bio-guoda/preston#160]
Suggest to use the example in https://github.com/bio-guoda/preston/issues/8#issuecomment-1095793252 as the default behavior for `preston origins` when no arguments are supplied and stdin is empty:
```
$ preston history\
 | tail -n1\
 | preston origins
```

Currently, running `preston origins` with no input/args just hangs forever.

**Comment by jhpoelen** [comment]
```preston cat``` also waits for input . . . as well as ```cat```

**Comment by jhpoelen** [comment]
How would you propose to change the behavior?

**Comment by jhpoelen** [comment]
I also like defaults, and . . . I like pipes too . . . 

So, I'd want to be able to do:

```
preston ls | preston origins 
```

or
 
```
preston history | preston origins
```

Can you see a way of making this work in addition to your proposed default behavior.

**Comment by mielliott** [comment]
Yeah! I agree that should be preserved. Sorry, I didn't realize that `preston cat` and `origin` etc. don't just hang, but the terminal itself becomes stdin and the user can type stuff in. Just like for `head` and `cat` and lots of other things. So let's forget the defaults I talked about. BUT I do thing a shortcut for this behavior is useful, so maybe a `preston history -r`/`--recursive` or `preston orgin -h`/`--head` ("head" meaning the latest entry in the hexastore index) or something along those lines.

I'm starting to feel less excited about this. In any case, at least I learned something today 😄

**Comment by jhpoelen** [comment]
I see how the ```preston history``` and ```preston origins``` are currently behaving a little differently. 

The origin of head make sense to me. Or the history of head. 

Equivalent might be the tail of history by default starting at the "big bang" and trying to make its way to head. 

Perhaps the ```preston future``` might make more sense for the ```preston history``` command: in that it shows a future of the "big bang" .

**Comment by jhpoelen** [comment]
Or see ```preston history``` as a history of head starting at the big bang.

**Comment by mielliott** [comment]
> Or see `preston history` as a history of head starting at the big bang.

Well, it gives the history of *one particular branch* that extends to the current head... starting at the big bang. I could definitely see newcomers to preston confusing "history" and "origin" with each other. Maybe a very literal `preston index` is more accurate than `preston history`? It's more of a "history of the observatory/index" than a "history of the head".

**Comment by jhpoelen** [comment]
In current preston version 

```
$ preston version
0.5.6
```

you `preston history` and `preston origins` do the same thing - 

List the history of a preston data package in reverse chronological order (more recent first) - 

When *no* anchor is provided, preston will try to find the most recent version using breadcrumbs / version index (`preston head`). Then the more recent version is used as an anchor.

When an anchor is provided, this version is inspected and dependencies to previous versions are resolved. 

In order words - 

```bash
preston history 
```

is the same as 

```bash
preston history --anchor $(preston head) 
```

Please re-open if you have remaining concerns.
