### ISSUE TITLE
meta.xml in hash://sha256/d47fa5353f0a5a78ac0eb74db37f89f1ac255b8065f75bc35bc124c62047035c uses xml escaped tabs/newlines

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/preston#161]
from #158 we found that dwca with content id hash://sha256/d47fa5353f0a5a78ac0eb74db37f89f1ac255b8065f75bc35bc124c62047035c failed to process. 

Suspected is that meta.xml uses xml escaped values for ```\t``` and ```\n``` to describe field delimiters and line terminators:

```
$ preston cat 'zip:hash://sha256/d47fa5353f0a5a78ac0eb74db37f89f1ac255b8065f75bc35bc124c62047035c!/meta.xml'
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<archive metadata="eml.xml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://rs.tdwg.org/dwc/text/">
    <core encoding="UTF-8" fieldsEnclosedBy='"' fieldsTerminatedBy="&#x9;" linesTerminatedBy="&#xA;" ignoreHeaderLines="1" rowType="http://rs.tdwg.org/dwc/terms/Occurrence">
        <files>
            <location>occurrence.txt</location>
        </files>
        <id index="0"/>
        <field index="1" term="http://rs.tdwg.org/dwc/terms/basisOfRecord"/>
        <field index="2" term="http://rs.tdwg.org/dwc/terms/catalogNumber"/>
        <field index="3" term="http://rs.tdwg.org/dwc/terms/collectionCode"/>
        <field index="4" term="http://rs.tdwg.org/dwc/terms/continent"/>
		<field index="5" term="http://rs.tdwg.org/dwc/terms/higherGeography"/>
        <field index="6" term="http://rs.tdwg.org/dwc/terms/country"/>
        <field index="7" term="http://rs.tdwg.org/dwc/terms/stateProvince"/>
		<field index="8" term="http://rs.tdwg.org/dwc/terms/locality"/>
		<field index="9" term="http://rs.tdwg.org/dwc/terms/verbatimEventDate"/>
		<field index="10" term="http://rs.tdwg.org/dwc/terms/eventDate"/>
	    <field index="11" term="http://rs.tdwg.org/dwc/terms/kingdom"/>
	    <field index="12" term="http://rs.tdwg.org/dwc/terms/family"/>
	    <field index="13" term="http://rs.tdwg.org/dwc/terms/genus"/>	
	    <field index="14" term="http://rs.tdwg.org/dwc/terms/subgenus"/>
        <field index="15" term="http://rs.tdwg.org/dwc/terms/specificEpithet"/>
	    <field index="16" term="http://rs.tdwg.org/dwc/terms/infraspecificEpithet"/>
        <field index="17" term="http://rs.tdwg.org/dwc/terms/verbatimTaxonRank"/>	
        <field index="18" term="http://rs.tdwg.org/dwc/terms/scientificNameAuthorship"/>		
		<field index="19" term="http://rs.tdwg.org/dwc/terms/scientificName"/>
        <field index="20" term="http://rs.tdwg.org/dwc/terms/typeStatus"/>
        <field index="21" term="http://rs.tdwg.org/dwc/terms/individualCount"/>
        <field index="22" term="http://rs.tdwg.org/dwc/terms/preparations"/>
        <field index="23" term="http://rs.tdwg.org/dwc/terms/recordedBy"/>
        <field index="24" term="http://rs.tdwg.org/dwc/terms/sex"/>
		<field index="25" term="http://rs.tdwg.org/dwc/terms/lifeStage"/>
        <field index="26" term="http://rs.tdwg.org/dwc/terms/occurrenceID"/>
        <field index="27" term="http://rs.tdwg.org/dwc/terms/nomenclaturalCode"/>	
        <field index="28" term="http://rs.tdwg.org/dwc/terms/institutionCode"/>   
    </core>
</archive>
```

@mdoering @tucotuco can ```"&#x9;``` and ```&#xA;``` be used instead of ```\t``` and ```\n```  in meta.xml row definitions?

**Comment by jhpoelen** [comment]
Note that the content is associated with https://doi.org/10.15468/17e8en https://www.gbif.org/dataset/62d82928-dc6f-40dc-85b3-f2be47e7b49a and  Creuwels J (2017). Naturalis Biodiversity Center (NL) - Museum collection digitized at storage unit level. Naturalis Biodiversity Center. Occurrence dataset https://doi.org/10.15468/17e8en accessed via GBIF.org on 2022-04-13. 

for some reason, the original source is no longer available. https://drive.google.com/uc?export=download&id=0B-BbRNUB6S7aSVdYSjNpbkZsM1E

**Comment by mdoering** [comment]
I think these entities are not part of the basic xml specs. It does work fine with the COL DwcaReader libraries though which uses the stax2 library to read the xml which does the unescaping.

**Comment by jhpoelen** [comment]
@mdoering thanks for your reply. Does this mean that you are no longer using the gbif-dwca-io lib? What is the relation between the COL DwcaReader and the GBIF DwcaReader?

**Comment by mdoering** [comment]
They are separate [implementations](https://github.com/CatalogueOfLife/backend/blob/master/webservice/src/main/java/life/catalogue/importer/dwca/DwcaReader.java) both building on the [dwc-api](https://github.com/gbif/dwc-api) that defines the terms. The COL version uses the univocity csv parser under the hood and has shares most logic and [code](https://github.com/CatalogueOfLife/backend/tree/master/webservice/src/main/java/life/catalogue/csv) with other tab file oriented readers like [ColDP](https://github.com/CatalogueOfLife/backend/blob/master/webservice/src/main/java/life/catalogue/importer/coldp/ColdpReader.java) and ACEF. That wasn't possible with the existing dwca-io which is build around the [star schema](https://github.com/gbif/dwca-io/blob/master/src/main/java/org/gbif/dwc/record/StarRecord.java). Not requiring gbif-common was also desirable.

If useful we could extract the various csv parsers into a lean module that allows reuse.

**Comment by jhpoelen** [comment]
@mdoering Thanks for the pointers! Yes, I much like your idea to create a lean module. 

Assuming that it'll take a while to create such a module, would you advise to use my own COL inspired version to avoid this reported issue?

Also, what code base is used for GBIF dataset indexing today? Or, what is today's use of dwca-io in the GBIF universe?

**Comment by jhpoelen** [comment]
BTW - just to give you an idea of how Preston implements the DwC-A json streamer on top of dwca-io , see - 

https://github.com/bio-guoda/preston/blob/4bb0a0037fd055d34b111067cca6c3ceed356e2f/preston-dwc/src/main/java/org/gbif/dwc/DwCArchiveStreamHandler.java

**Comment by jhpoelen** [comment]
@mdoering after implementing a unit test to reproduce the issue of the  "&#x9; and &#xA; be used instead of \t and \n in meta.xml row definitions, I found that these values were parsed ok, but ignored, because of a suspected bug in https://github.com/gbif/dwca-io/blob/7cd05e21ebbc0dece62c9e73be41e2e898959073/src/main/java/org/gbif/dwc/meta/MetaXMLSaxHandler.java#L82 

and 

https://github.com/gbif/dwca-io/blob/7cd05e21ebbc0dece62c9e73be41e2e898959073/src/main/java/org/gbif/dwc/meta/MetaXMLSaxHandler.java#L92

the getAttr method uses StringUtils.isBlank and this filters out the encoded control characters like ```\t``` and ```\n```. I've added a patched version in my own code base via https://github.com/bio-guoda/preston/commit/c5bbc6ec328c63af7fe990be44b991d5488bd3a1

Are you still maintaining/ using dwca-io ? If so, how would you like to proceed in fixing this issue.

**Comment by jhpoelen** [comment]
Root cause appeared to be a bug in the gbif dwca-io lib. 

After patch, the following result was found:

```
# get content
$ preston cat --remote https://deeplinker.bio hash://sha256/d47fa5353f0a5a78ac0eb74db37f89f1ac255b8065f75bc35bc124c62047035c > funky.zip
# track content
$ preston track file://$PWD/funky.zip
...
# print first json record
$ preston ls | grep funky | preston dwc-stream | head -n1 | jq .
```

and the following output was produced:

```json
{
  "http://www.w3.org/ns/prov#wasDerivedFrom": "line:zip:hash://sha256/d47fa5353f0a5a78ac0eb74db37f89f1ac255b8065f75bc35bc124c62047035c!/occurrence.txt!/L2",
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#type": "http://rs.tdwg.org/dwc/terms/Occurrence",
  "http://rs.tdwg.org/dwc/terms/genus": "Apodemus",
  "http://rs.tdwg.org/dwc/terms/recordedBy": null,
  "http://rs.tdwg.org/dwc/terms/continent": null,
  "http://rs.tdwg.org/dwc/terms/sex": null,
  "http://rs.tdwg.org/dwc/terms/basisOfRecord": "StorageUnit",
  "http://rs.tdwg.org/dwc/terms/scientificName": "Apodemus sylvaticus Linnaeus, 1758",
  "http://rs.tdwg.org/dwc/terms/preparations": null,
  "http://rs.tdwg.org/dwc/terms/infraspecificEpithet": null,
  "http://rs.tdwg.org/dwc/terms/individualCount": null,
  "http://rs.tdwg.org/dwc/terms/eventDate": null,
  "http://rs.tdwg.org/dwc/terms/institutionCode": "Naturalis",
  "http://rs.tdwg.org/dwc/terms/verbatimEventDate": null,
  "http://rs.tdwg.org/dwc/terms/locality": null,
  "http://rs.tdwg.org/dwc/terms/catalogNumber": "BE.0000001",
  "http://rs.tdwg.org/dwc/terms/stateProvince": null,
  "http://rs.tdwg.org/dwc/terms/family": "Muridae",
  "http://rs.tdwg.org/dwc/terms/lifeStage": null,
  "http://rs.tdwg.org/dwc/terms/subgenus": null,
  "http://rs.tdwg.org/dwc/terms/typeStatus": null,
  "http://rs.tdwg.org/dwc/terms/collectionCode": "Mammalia",
  "http://rs.tdwg.org/dwc/terms/kingdom": "Animalia",
  "http://rs.tdwg.org/dwc/terms/scientificNameAuthorship": "Linnaeus, 1758",
  "http://rs.tdwg.org/dwc/terms/country": null,
  "http://rs.tdwg.org/dwc/terms/verbatimTaxonRank": "species",
  "http://rs.tdwg.org/dwc/terms/specificEpithet": "sylvaticus",
  "http://rs.tdwg.org/dwc/terms/nomenclaturalCode": "ICZN",
  "http://rs.tdwg.org/dwc/terms/occurrenceID": "BE.0000001_20405621",
  "http://rs.tdwg.org/dwc/terms/higherGeography": null
}
```
