### ISSUE TITLE
Suspiciously large dwcA files in Preston archive ver 38

### ISSUE THREAD

**Issue by pgasu** [bio-guoda/preston#163]
While scanning through version 38 of Preston archive for GBIF, I encountered three suspiciously large files - the corresponding hashes are following:
- hash://sha256/9f8c0ed6b6dae0517f21db8f01179f666b4ae4b477814d028a9f03d68dcf9ff7
- hash://sha256/ec3ff57cb48d5c41b77b5d1075738b40f598a900e8be56e7645e5a24013dffc4
- hash://sha256/ee7134043e02f845643b6a655e1c3ffe6d406d0002f8089c5399f0df418b80d6

The size of dwca zip files corresponding to these hashes are  6.5Gb, 20Gb and 20Gb respectively, and the unzipped occurrence.txt files come out to be 75G, 156G and 155G respectively. 
I further inspected the first dwca - the eml.xml file suggests the dataset is uploaded from http://www.gbif.se/ipt/resource?r=artdata 
I checked the version I downloaded, and it looks like the size is correct. If all these are genuinely big files, what is the best approach to read and access data from them?

**Comment by jhpoelen** [comment]
yep, there are some really big dwca out there. 

Half of GBIF's occurrences sits in the single eBird dwca . 

I like to stream data from these big files using ```preston dwc-stream``` or ```unzip -p huge.zip somefile.txt``` . 

Curious to hear what you come up with or whether you have any remaining issues.

**Comment by jhpoelen** [comment]
you can check the emls using

```preston cat `zip:hash://sha256/ec3ff57cb48d5c41b77b5d1075738b40f598a900e8be56e7645e5a24013dffc4!/eml.xml'``` or similar.

**Comment by pgasu** [comment]
I guess, I am going to run these files separately on compute nodes, and then let it take its own time. 
For now I am trying to download all these datasets for the specific versions I require. I will share my progress and concern as I move along.

**Comment by jhpoelen** [comment]
ok. Why run them on a separate node? Do they fill-up your disks? 

Note that you can do --no-cache option to avoid accumulating all the stuff you've already processed.

**Comment by jhpoelen** [comment]
Just holler if you have ideas for necessary functionality or when you have additional questions.

Very curious about your outcomes!

**Comment by pgasu** [comment]
Well, normally download the data locally, and I have received warning/error related to /tmp directory being full. Also, reading through such big files would take long time - running it on a compute node doesn't make me worry about disconnection or other network errors.

**Comment by jhpoelen** [comment]
@pgasu thanks for clarifying the reasons why you decided to process the bigger dwca elsewhere. I am sure you are not alone is having these hard disk and time constraints. 

Would it help to have some kind of way to say: "hey Preston, get me all this stuff, but only use up to 15GB of the local hard disk." ?

Also, I'd be curious to learn how long it would actually take to generate the >500M json records from the eBird dwca. What is the maximum time you'd want to spend on a single dwca?

**Comment by PietrH** [comment]
I have some experience in working with occurrence data of this size, and while I can do my processing locally (or on the dev server), I've also used clusters/cloud in the past ([databricks on MS Azure](https://planetarycomputer.microsoft.com/), Flemish Supercomputer Centre, Google Colab).

If you are looking at distributed processing, or are having trouble with running out of memory you could use out of memory processing or things like Apache arrow. GBIF actually has (undocumented) support for Apache parquet exports: https://data-blog.gbif.org/post/apache-arrow-and-parquet/

Depending on the hardware of course, I can parse/read a 150GB occurrence file in under 2 minutes, which about the time it takes me to wonder if I should start looking for a faster solution. I use data.table in R (https://github.com/Rdatatable/data.table) for out of memory efficient processing, a fork for [Python](https://towardsdatascience.com/an-overview-of-pythons-datatable-package-5d3a97394ee9) exists. For my personal big data needs I use Apache Spark. 

Loading a big occurrence file into Spark takes longer, but mounting [a very significant margin of all records on gbif](https://registry.opendata.aws/gbif/) doesn't take longer than I'm willing to wait. Somewhere between 5 and 20 minutes I'm guessing, probably depends a lot on your setup.

In my experience, uncompressing takes longer than the actual reading the of the file. [pigz ](https://linux.die.net/man/1/pigz)helps a lot in that regard.

**Comment by jhpoelen** [comment]
@PietrH thanks for sharing your experience.

Some years ago, I also worked with the Apache Spark / HDFS / Kafka stack. . . and I found them impressive systems also found them to be tricky to tune and keep up and running - 

Thessen AE, Poelen JH, Collins M, Hammock J. 20 GB in 10 minutes: a case for linking major biodiversity databases using an open socio-technical infrastructure and a pragmatic, cross-institutional collaboration. PeerJ Comput Sci. 2018 Sep 17;4:e164. doi: 10.7717/peerj-cs.164. PMID: 33816817; PMCID: PMC7924439. @diatomsRcool @jhammock 

```[...] The bottlenecks in processing for Hadoop File System and Apache Spark are the number of CPUs, amount of memory, and available storage space allocated to the computer cluster. Both HDFS and Spark are designed to scale horizontally by adding commodity servers (aka nodes) to increase the processing power, working memory, and storage space. Thus, this problem is immediately solvable. Internet bandwidth to transfer the data archives from Open Tree of Life, Wikidata, and GloBI does not scale and is not something that can be addressed solely within our research group. At the moment, it takes longer to download the Wikidata resource than it does to run the linking process discussed in this manuscript. [...]```


This experience system actually inspired many of the Preston features:

1. migrating away from location-based to content-based identifiers to work around ```[...]  Internet bandwidth to transfer the data archives from Open Tree of Life, Wikidata, and GloBI does not scale [...]``` allowing for decentralized, offline-enabled, storage
2. streaming directly from unaltered (zip) archives instead of having to unzip / preprocess them first
3. easy to install offline-enabled command-line tools (e.g., [preston](https://github.com/bio-gupda/preston), [nomer](https://github.com/globalbioticinteractions/nomer))
4. modular commands taking and producing streams (e.g., history, ls, cat, grep, dwc-stream) allow for parallelized workflows using ```xargs``` or ```parallel``` while keeping the door open for more complex solutions like apache kafka, apache spark etc.

Hopefully, discussions like these can help folks find the data and tools that work for best them. And, perhaps I get some inspiration for making existing tools a little more useful.

**Comment by PietrH** [comment]
I have certainly noticed some of these complications with Spark. Personally, depending on the task I'll process it completely locally using data.table, on a local spark instance or on a spark cluster somewhere in a datacenter. Spark and Arrow are certainly less approachable than a simple csv, and I want to stress that while maybe not optimal, handling 100GB+ text files locally using interpreted languages like Python and R is still within the capabilities of my laptop and the limits of my patience. Spark really shines in big table joins and optimizing complex filter operations (mapreduce I suppose).

**Comment by jhpoelen** [comment]
fyi @cboettig

**Comment by pgasu** [comment]
> Would it help to have some kind of way to say: "hey Preston, get me all this stuff, but only use up to 15GB of the local hard disk." ?

I can see why this can be a really good feature for someone who doesn't have access to compute resources. If I have to work it locally on my machine, it would be very helpful to know the memory and disk space requirements, and restrict the required resources based on availability. This makes me curious about how 'Preston dwc-stream' works? It looks like it doesn't download the whole data, because my data folder still shows 96G, although I scanned through the complete version 38, including those large ~150G files. But I also noticed that it first scans through the whole data, and only then output the results, because it took several hours for reading/downloading the large eBird dwca, before it starts writing which took just few minutes. Does it keep the data in tmp folder or in memory? It would be nice to know what goes behind the scene - May be we can then parallelize dwc-stream process by splitting the file into multiple parts?

> Also, I'd be curious to learn how long it would actually take to generate the >500M json records from the eBird dwca. What is the maximum time you'd want to spend on a single dwca?

It actually took 372 mins (~ 6 hrs) to read through the eBird dwca. I was so involved in the technical sides of things that I forgot that I am only interested in mammal data for the current project, and realized I really didn't need to go through eBird data. Anyways, it was fun exercise. Regarding how much time I would like to spend on a single dwca, I guess it's a matter of requirements of the project. In my case, I would wait even if it takes a day or two. I believe what bothers, in general, is the reliability of the process and the debugging turnaround time in large files.

**Comment by jhpoelen** [comment]
@pgasu hey Prashant, please let me know if I addressed this issue re: suspiciously large DwC-A files in Person archive v. 38. 

Also, I'd be curious to hear what method you ended up using, especially if you chose not to go the Preston route.

Hope all is well!

**Comment by jhpoelen** [comment]
Please feel free to comments / re-open if you have unresolved issues.

fyi @n8upham

**Comment by n8upham** [comment]
Thanks Jorrit -- @pgasu is re-visiting some aspects of this project in the next few days, so I can let you know if we have additional questions.

**Comment by jhpoelen** [comment]
@n8upham thanks for responding. Assuming that you and @pgasu have no additional question at this point, so I am closing this issue. Happy to re-open if questions come up related to the topic of large dwca in Preston archives.
