### ISSUE TITLE
include preston version in provenance logs

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/preston#17]

**Comment by jhpoelen** [comment]
Previously, no reference to a Preston version could be found in the provenance logs. 

I've added a reference to the Zenodo publication doi and bibliographic citation of Preston source code as used by the generation activity. The version information is populated by the version stamped into the Preston jar. For development versions, this would be 0.0.1-SNAPSHOT, for release version, this would be e.g. ```0.2.12 ```.
```
<https://doi.org/10.5281/zenodo.1410543> <http://www.w3.org/ns/prov#usedBy> <3de48a6d-1c22-4fcb-b72d-b4338e17e54c> .
<https://doi.org/10.5281/zenodo.1410543> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.org/dc/dcmitype/Software> .
<https://doi.org/10.5281/zenodo.1410543> <http://purl.org/dc/terms/bibliographicCitation> "Jorrit Poelen, Icaro Alzuru, & Michael Elliott. 2019. Preston: a biodiversity dataset tracker (Version 0.0.1-SNAPSHOT) [Software]. Zenodo. http://doi.org/10.5281/zenodo.3334454"@en .
```

@ialzuru @mielliott Kindly review and close issue if this issue has been solved.

**Comment by mielliott** [comment]
cool, closing.
