### ISSUE TITLE
past crawl logs missing some wasGeneratedBy lines

### ISSUE THREAD

**Issue by mielliott** [bio-guoda/preston#18]
For crawls up to and including 2019-01-07, about 2/3 of URL queries do not have an accompanying ```wasGeneratedBy```.

For example, URLs from portal.torcherbaria.org in the 2019-01-07 crawl log (hash://sha256/a7a5e7c6a4b21bdf67f48d6bea85f438b8133f674027b04625dfadec3ff985f6):
```shell
...
<http://portal.torcherbaria.org/portal/content/dwca/TAC_DwC-A.zip> <http://purl.org/dc/elements/1.1/format> "application/dwca" .
<http://portal.torcherbaria.org/portal/content/dwca/TAC_DwC-A.zip> <http://purl.org/pav/hasVersion> <hash://sha256/e961b979c14f4275918c7e9280b899d3a141b9129edbabe6d243f1aa6f96d524> .
<hash://sha256/72a78747b822a861abd4bb4e1af1e250a2521c6f070c60308eb0a9d18fafdf00> <http://www.w3.org/ns/prov#generatedAtTime> "2018-08-31T18:38:43.091Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
<hash://sha256/72a78747b822a861abd4bb4e1af1e250a2521c6f070c60308eb0a9d18fafdf00> <http://www.w3.org/ns/prov#hadMember> <6ade07ee-25bf-49c8-ae19-f7c225f70422> .
...
```

Crawl logs up to 2019-01-07 have fewer ```wasGeneratedBy``` than  ```hasVersion``` statements:
```shell
$ preston get hash://sha256/a7a5e7c6a4b21bdf67f48d6bea85f438b8133f674027b04625dfadec3ff985f6 | grep "wasGeneratedBy" | wc -l
30602
$ preston get hash://sha256/a7a5e7c6a4b21bdf67f48d6bea85f438b8133f674027b04625dfadec3ff985f6 | grep "hasVersion" | wc -l
101155
```
while all crawl logs afterward (2019-02-04 and later) have equal numbers:
```shell
$ preston get hash://sha256/af0bb2c89571a30815d4488e72dede84a2ffc102bb87961f06884509fd5d1dae | grep "wasGeneratedBy" | wc -l
56924
$ preston get hash://sha256/af0bb2c89571a30815d4488e72dede84a2ffc102bb87961f06884509fd5d1dae | grep "hasVersion" | wc -l
56924
```
Maybe we can retroactively generate the missing ```wasGeneratedBy``` statements (or, even better, ```qualifiedGeneration```s) and add them to the Preston log using ```preston reprocess```?

**Comment by jhpoelen** [comment]
From what I can tell, all versions generated after 2019-01-06 in 2019-01-07 crawl log hash://sha256/a7a5e7c6a4b21bdf67f48d6bea85f438b8133f674027b04625dfadec3ff985f6 have wasGeneratedBy statements. 

I ran sparql query:
```sparql
SELECT ?count {
{
  SELECT (COUNT(*) as ?count)
  WHERE {
    ?s <http://www.w3.org/ns/prov#generatedAtTime> ?date .
    FILTER NOT EXISTS { ?s <http://www.w3.org/ns/prov#wasGeneratedBy> ?crawl . }
    FILTER (?date > "2019-01-06T10:20:13Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>)
}
}

UNION
{
SELECT (COUNT(*) as ?count)
WHERE {
  ?s <http://www.w3.org/ns/prov#generatedAtTime> ?date .
  FILTER EXISTS { ?s <http://www.w3.org/ns/prov#wasGeneratedBy> ?crawl . }
  FILTER (?date > "2019-01-06T10:20:13Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>)
}
}
}
```
and found:
```
----------------------------------------------------------
| count | desc                                           |
==========================================================
| 0     | "generations without wasGeneratedBy statement" |
| 30602 | "generations with wasGeneratedBy statement"    |
----------------------------------------------------------
```

Given the that all the previous version of known URLs were captured prior to 2019-02 and that only generations (aka downloads) in the current crawl will have a wasGeneratedBy statement, I would expect the number of wasGeneratedBy statement to be lower than the version (i.e. previousVersion / hasVersion) statements.

@mielliott Please confirm that this is not a bug, but expected behavior.

**Comment by jhpoelen** [comment]
btw - I used https://jena.apache.org tools ```tdbload``` ```tdbquery```,  ```sparql``` to run these queries from the command line. The tdb* tools are using an indexed logs (so, first index, then query), whereas the ```sparql``` commandline tools allows for running a query on a nquad file (e.g., ```./sparql --data=.../somelog.nq --query=noWasGenerated.sparql```).

**Comment by mielliott** [comment]
@jhpoelen I agree. Closing.
