### ISSUE TITLE
"No provenance found" when cloning Big-Bee's Internet Archive dataset

### ISSUE THREAD

**Issue by mielliott** [bio-guoda/preston#182]
In reference to https://github.com/bio-guoda/preston/issues/166#issuecomment-1203009967_

Looks like the Internet Archive dataset is mis-bee-having (sorry).

```
$ preston clone https://archive.org/download/preston-ucsb-izc/data.zip/
[https://archive.org/down...210ef59e06b640a3539cb5a] 0 bytes at 0.00 MB/s completed in < 1 minute
[https://archive.org/down...c5fb6d7de3b353a0a165e42] 0 bytes at 0.00 MB/s completed in < 1 minute
[main] WARN bio.guoda.preston.cmd.ReplayUtil - No provenance found. Please use/create a Preston data archive.
```

@jhpoelen

**Comment by mielliott** [comment]
Looks like https://archive.org/download/preston-ucsb-izc/data.zip/2a/5d/2a5de79372318317a382ea9a2cef069780
b852b01210ef59e06b640a3539cb5a returns a redirect
```
$ curl -i https://archive.org/download/preston-ucsb-izc/data.zip/2a/5d/2a5de79372318317a382ea9a2cef069780b852b01210ef59e06b640a3539cb5a | head -n1
HTTP/1.1 302 Found
```

So redirects need to be followed to get any data:

```
$ curl -L https://archive.org/download/preston-ucsb-izc/data.zip/2a/5d/2a5de79372318317a382ea9a2cef069780
b852b01210ef59e06b640a3539cb5a
hash://sha256/d5eb492d3e0304afadcc85f968de1e23042479ad670a5819cee00f2c2c277f36
```

Maybe preston isn't following redirects for remotes?

**Comment by jhpoelen** [comment]
@mielliott finally got around addressing this "no provenance found" issue. 

Root cause was that Preston wasn't detecting invalid query results. Now, an IOException is thrown when a remote returns content that does not match the query. In case of hexastore queries, a result is valid if the result is a hash uri string. In case of a content query, the hash of the result should match the query key. With this, Preston is able to try alternative locations / strategies before calling it quits, allowing for redundancies and failover strategies. 

Now, the expected behavior is seen:

```
$ preston clone https://archive.org/download/preston-ucsb-izc/data.zip/ | tee log.txt
[https://archive.org/down...210ef59e06b640a3539cb5a] 0 bytes at 0.00 MB/s completed in < 1 minute
[https://archive.org/down...210ef59e06b640a3539cb5a] 78 bytes at 0.04 MB/s completed in < 1 minute
[https://archive.org/down...70a5819cee00f2c2c277f36] 0 bytes at 0.00 MB/s completed in < 1 minute
[https://archive.org/down...70a5819cee00f2c2c277f36] 66 MB at 11.13 MB/s^C
```

and 

```
$ preston history
<urn:uuid:0659a54f-b713-4f86-a917-5be166a14110> <http://purl.org/pav/hasVersion> <hash://sha256/d5eb492d3e0304afadcc85f968de1e23042479ad670a5819cee00f2c2c277f36> .
```

**Comment by jhpoelen** [comment]
btw - Preston did already follow http redirects.

**Comment by mielliott** [comment]
Very nice @jhpoelen, good to see this fixed. The added verification steps make me feel a lot better about pitching content delivery networks built on --remotes.
