### ISSUE TITLE
Add an option to verify dereferenced content?

### ISSUE THREAD

**Issue by mielliott** [bio-guoda/preston#183]
For example, if I run

```
preston clone --remote https://example1.org/data,https://example2.org/data
```

The first thing preston will try to retrieve is https://example1.org/data/2a5de79372318317a382ea9a2cef069780b852b01210ef59e06b640a3539cb5a

Suppose that URL returns an error page or empty content (as in #182 and https://github.com/bio-guoda/preston/issues/166#issuecomment-1203009967) instead of the referenced data, preston will keep chugging along as if it retrieved the correct data. If preston could check the hash of the downloaded data, it could see that it was wrong, then try another remote instead.

Something like

```
preston clone --verify --remote [remotes...]
```

**Comment by jhpoelen** [comment]
possibly related to #182

**Comment by jhpoelen** [comment]
and https://github.com/bio-guoda/preston/issues/166#issuecomment-1203009967

**Comment by jhpoelen** [comment]
as described in https://github.com/bio-guoda/preston/issues/182#issuecomment-1256572892 , the content is now validated unless the local cache is disabled with the ```--no-cache``` command.
