### ISSUE TITLE
gbif registry reader aborts early if no/bad content is returned

### ISSUE THREAD

**Issue by mielliott** [bio-guoda/preston#21]
Currently, the registry reader for GBIF stops querying the GBIF API when either "endOfRecords:true" is found or when the query results could not be parsed.
https://github.com/bio-guoda/preston/blob/fc638c4faaf470110131be01b95355a46d62fb64/src/main/java/bio/guoda/preston/process/RegistryReaderGBIF.java#L110

The crawl on 2019-03-01 stopped short because a single query to ```https://api.gbif.org/v1/dataset?offset=8560&limit=20``` did not produce parsable results and Preston assumed that was the end of GBIF's records.

Examples of a stopped crawl and a successful crawl:
- 2019-03-01 (bad crawl, 428 pages queried): https://deeplinker.bio/261177a96185166f1c301beacf7350abff03d1b5710be6bfd8c4aff9caffef12
- 2019-02-04 (good crawl, 2108 pages queried): https://deeplinker.bio/af0bb2c89571a30815d4488e72dede84a2ffc102bb87961f06884509fd5d1dae

So, for api.gbif.org, is there a better way to get the total number of datasets or to detect when to stop querying pages? @mdoering @jhpoelen

**Comment by jhpoelen** [comment]
@mielliott thanks for sharing. You mentioned that non-parsable results were generated. Was this malformed json or some error code resulting in a blank node?

**Comment by mielliott** [comment]
> @mielliott thanks for sharing. You mentioned that non-parsable results were generated. Was this malformed json or some error code resulting in a blank node?

I was trying to be careful how I worded that; RegistryReaderGBIF only checks if a ```JsonNode``` could be parsed from the result of the query, and I assume this check failed in the March crawl.
https://github.com/bio-guoda/preston/blob/fc638c4faaf470110131be01b95355a46d62fb64/src/main/java/bio/guoda/preston/process/RegistryReaderGBIF.java#L95
https://github.com/bio-guoda/preston/blob/fc638c4faaf470110131be01b95355a46d62fb64/src/main/java/bio/guoda/preston/process/RegistryReaderGBIF.java#L110
However, the last line in the March log shows a ```genid``` was returned, so I assume it was a 404 error or something:
```
<https://api.gbif.org/v1/dataset?offset=8560&limit=20> <http://purl.org/pav/hasVersion> <https://deeplinker.bio/.well-known/genid/1b9bd20f-42ab-3014-bf0a-dd9af23664be> .
```

**Comment by jhpoelen** [comment]
@mielliott thanks  for clarifying. This does look like a some temporary network outage or server error. I wish there was a way to retrieve the entire GBIF registry in one go.

**Comment by mdoering** [comment]
querying the GBIF registry via `https://api.gbif.org/v1/dataset?offset=8560&limit=20` and looking for the endOfRecords flag is an expected use. If you experience unparsable, bad responses please [log an issue with GBIF](https://github.com/gbif/registry/issues). If you plan to page through all datasets using a larger limit of 100 or 500 would help.

**Comment by mielliott** [comment]
Thanks @mdoering for the insight. Rather than using our current ```endOfRecords``` check for paging through the datasets, maybe we should use ```count``` to build a list of queries to submit and continue submitting them even if one fails. Then, we can keep querying successive pages until ```endOfRecords``` is met or we don't receive a response.

**Comment by jhpoelen** [comment]
@mielliott @mdoering am now submitting all pages at once using the default page size provided by GBIF api (i.e. 20). I am assuming that the default page size is tuned so that pages can be efficiently retrieved. Will open pull request to increase the default in the GBIF api to reflect @mdoering suggestion.

**Comment by jhpoelen** [comment]
The subject of this issue has been addressed by submitting all gbif dataset registry pages at once. Eager to replace this with a non-paginated solution, like suggested in https://github.com/gbif/registry/issues/147 . Improvement made available in https://github.com/bio-guoda/preston/releases/tag/0.1.4 .

@mielliott please re-open / comment if you feel this issue was not properly addressed.
