### ISSUE TITLE
preston ls -l tsv no longer produces tsv 

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/preston#220]
preston ls -l tsv 

is supposed to produce tsv output instead of the default nquads. 

For some reason, this is not happening. 

However, 

preston history -l tsv is producing tsv output.

**Comment by jhpoelen** [comment]
Now, after running `preston track https://example.org` , 

`preston ls -l tsv` produced:

```
https://preston.guoda.bio	http://www.w3.org/1999/02/22-rdf-syntax-ns#type	http://www.w3.org/ns/prov#SoftwareAgent	urn:uuid:88948228-e967-415c-8cc6-b3f4b4c77a26
https://preston.guoda.bio	http://www.w3.org/1999/02/22-rdf-syntax-ns#type	http://www.w3.org/ns/prov#Agent	urn:uuid:88948228-e967-415c-8cc6-b3f4b4c77a26
https://preston.guoda.bio	http://purl.org/dc/terms/description	Preston is a software program that finds, archives and provides access to biodiversity datasets.	urn:uuid:88948228-e967-415c-8cc6-b3f4b4c77a26
urn:uuid:88948228-e967-415c-8cc6-b3f4b4c77a26	http://www.w3.org/1999/02/22-rdf-syntax-ns#type	http://www.w3.org/ns/prov#Activity	urn:uuid:88948228-e967-415c-8cc6-b3f4b4c77a26
urn:uuid:88948228-e967-415c-8cc6-b3f4b4c77a26	http://purl.org/dc/terms/description	A crawl event that discovers biodiversity archives.	urn:uuid:88948228-e967-415c-8cc6-b3f4b4c77a26
urn:uuid:88948228-e967-415c-8cc6-b3f4b4c77a26	http://www.w3.org/ns/prov#startedAtTime	2023-04-13T02:25:42.491Z	urn:uuid:88948228-e967-415c-8cc6-b3f4b4c77a26
urn:uuid:88948228-e967-415c-8cc6-b3f4b4c77a26	http://www.w3.org/ns/prov#wasStartedBy	https://preston.guoda.bio	urn:uuid:88948228-e967-415c-8cc6-b3f4b4c77a26
https://doi.org/10.5281/zenodo.1410543	http://www.w3.org/ns/prov#usedBy	urn:uuid:88948228-e967-415c-8cc6-b3f4b4c77a26	urn:uuid:88948228-e967-415c-8cc6-b3f4b4c77a26
https://doi.org/10.5281/zenodo.1410543	http://www.w3.org/1999/02/22-rdf-syntax-ns#type	http://purl.org/dc/dcmitype/Software	urn:uuid:88948228-e967-415c-8cc6-b3f4b4c77a26
https://doi.org/10.5281/zenodo.1410543	http://purl.org/dc/terms/bibliographicCitation	Jorrit Poelen, Icaro Alzuru, & Michael Elliott. 2021. Preston: a biodiversity dataset tracker (Version 0.5.7-SNAPSHOT) [Software]. Zenodo. http://doi.org/10.5281/zenodo.1410543	urn:uuid:88948228-e967-415c-8cc6-b3f4b4c77a26
urn:uuid:0659a54f-b713-4f86-a917-5be166a14110	http://www.w3.org/1999/02/22-rdf-syntax-ns#type	http://www.w3.org/ns/prov#Entity	urn:uuid:88948228-e967-415c-8cc6-b3f4b4c77a26
urn:uuid:0659a54f-b713-4f86-a917-5be166a14110	http://purl.org/dc/terms/description	A biodiversity dataset graph archive.	urn:uuid:88948228-e967-415c-8cc6-b3f4b4c77a26
hash://sha256/ea8fac7c65fb589b0d53560f5251f74f9e9b243478dcb6b3ea79b5e36449c8d9	http://www.w3.org/ns/prov#wasGeneratedBy	urn:uuid:85fb9fca-75a3-4eda-b6cd-0c8e007a2fa4	urn:uuid:85fb9fca-75a3-4eda-b6cd-0c8e007a2fa4
hash://sha256/ea8fac7c65fb589b0d53560f5251f74f9e9b243478dcb6b3ea79b5e36449c8d9	http://www.w3.org/ns/prov#qualifiedGeneration	urn:uuid:85fb9fca-75a3-4eda-b6cd-0c8e007a2fa4	urn:uuid:85fb9fca-75a3-4eda-b6cd-0c8e007a2fa4
urn:uuid:85fb9fca-75a3-4eda-b6cd-0c8e007a2fa4	http://www.w3.org/ns/prov#generatedAtTime	2023-04-13T02:25:42.978Z	urn:uuid:85fb9fca-75a3-4eda-b6cd-0c8e007a2fa4
urn:uuid:85fb9fca-75a3-4eda-b6cd-0c8e007a2fa4	http://www.w3.org/1999/02/22-rdf-syntax-ns#type	http://www.w3.org/ns/prov#Generation	urn:uuid:85fb9fca-75a3-4eda-b6cd-0c8e007a2fa4
urn:uuid:85fb9fca-75a3-4eda-b6cd-0c8e007a2fa4	http://www.w3.org/ns/prov#wasInformedBy	urn:uuid:88948228-e967-415c-8cc6-b3f4b4c77a26	urn:uuid:85fb9fca-75a3-4eda-b6cd-0c8e007a2fa4
urn:uuid:85fb9fca-75a3-4eda-b6cd-0c8e007a2fa4	http://www.w3.org/ns/prov#used	https://example.org	urn:uuid:85fb9fca-75a3-4eda-b6cd-0c8e007a2fa4
https://example.org	http://purl.org/pav/hasVersion	hash://sha256/ea8fac7c65fb589b0d53560f5251f74f9e9b243478dcb6b3ea79b5e36449c8d9	urn:uuid:85fb9fca-75a3-4eda-b6cd-0c8e007a2fa4
```

**Comment by jhpoelen** [comment]
Note however, that when relative URIs or other funky quads are encountered, errors occur, lines are not produced. 

Perhaps best to drop support for tsv re-formatting in favor of simplicity and consistency - preston's goal is not to reformat nquads into tsv, and having inconsistent results for ```preston ls``` depending on the output format is confusing (at least to me).

@mielliott any thought on this?

**Comment by mielliott** [comment]
> or other funky quads are encountered, errors occur, lines are not produced.

That ain't good!

> Perhaps best to drop support for tsv re-formatting in favor of simplicity and consistency - preston's goal is not to reformat nquads into tsv, and having inconsistent results for preston ls depending on the output format is confusing (at least to me).

The TSV transformation is super useful, and I haven't encountered a small command line tool that does this neatly. What about just changing the delimiter between terms? Either changing how `-l tsv` works or using something like `-d \t` (as `cut` does). I don't think the n-quads spec cares, as long as it's whitespace. Then the n-quads can also be TSV. We can leave it to someone in the future to make a tool to convert n-quads to no-quads (change <horse> to horse, etc.)

**Comment by jhpoelen** [comment]
> The TSV transformation is super useful, and I haven't encountered a small command line tool that does this neatly. 

I much agree. The thing about the spaces is that (object) literals may have spaces. I am now (grudgingly) playing around with a mix of regexes to implement some non-validating rdf parser. Can't be that hard right . . . :fearful:

**Comment by mielliott** [comment]
> The thing about the spaces is that (object) literals may have spaces.

The parser we uses handles these just fine though, and when preston outputs n-quads it rebuilds them from the terms, so we shouldn't need to worry about spaces/tabs/etc. in literals, right? Just separate them with, say, tabs, newlines, spaces, forty spaces, etc. It would be the user's job to parse literals correctly

**Comment by jhpoelen** [comment]
RDF4J appears to choke on IRIs like `<f0fb6561-0646-42af-bf12-117d571189b1> ` - they can be ignored, and no way to just say . . . 'hey man, gimme a break, just take those crappy IRIs."

**Comment by mielliott** [comment]
Ahhhh. It really wants the `uuid:` prefix? So it's a general problem with the parser, not just when trying to output TSV?

**Comment by jhpoelen** [comment]
This leads to a large conversation - in which Preston supports any kind of text format, with increased understanding when encountering (embedded) nquad-like phrases. This would help make write "normal" READMEs with embedded nquads, or even just content ids and leave Preston with something to chew on.

**Comment by jhpoelen** [comment]
> Ahhhh. It really wants the uuid: prefix? So it's a general problem with the parser, not just when trying to output TSV?

Yeah, Jena's parser was a little more lenient in that way. But RDF4J has some nice stream parsing features.

**Comment by jhpoelen** [comment]
I've introduce another approach to nquad interpretation - this one supports quads with graphlabels and without blanks. 

```preston clone "https://jhpoelen.nl/bees/data"``` 

`preston ls -l tsv | head -n1` now produces:

```
https://preston.guoda.bio	http://www.w3.org/1999/02/22-rdf-syntax-ns#type	http://www.w3.org/ns/prov#SoftwareAgent	d2c8a96a-89c8-4dd6-ba37-06809d4ff9ae
```
