### ISSUE TITLE
OBIS and ALA Observatories

### ISSUE THREAD

**Issue by partha04patel** [bio-guoda/preston#23]
Establish observatories for OBIS and ALA on Preston servers.

**Comment by jhpoelen** [comment]
Suggest to use https://github.com/bio-guoda/preston#running-periodically recipe and run monthly . Install separate observatories at ACIS and Germany.

**Comment by jhpoelen** [comment]
@partha04patel @mielliott I've enabled ALA and OBIS repositories on Germany server using https://github.com/bio-guoda/preston#running-periodically .

```console
$ systemctl --type timer
preston-ala.timer            loaded active waiting Run Preston ALA                                            
preston-bhl.timer            loaded active waiting Run Preston Biodiversity Heritage Library                  
preston-dataone.timer        loaded active waiting Run Preston DataONE                                        
preston-obis.timer           loaded active waiting Run Preston OBIS   
```
I was careful to configure separate work dirs to avoid overlapping repos.

Please close this issue once you've established observatories @ ACIS .

**Comment by jhpoelen** [comment]
@partha04patel am closing issue, since the observatory is running in Germany. You can do the same in other locations with provided instructions if you'd like.
