### ISSUE TITLE
support linking of specific page numbers in pdf content https://www.w3.org/TR/WCAG20-TECHS/PDF17.html

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/preston#308]
Some pdf documents are quite large while citations into these documents are quite specific. 

For instance, a dental formula in Koopman 1994 can be found on original page 19 (or pdf page 27)

https://linker.bio/hash://md5/70c3e0fba7379e09e95a38569fe29da7#page=27

perhaps introduce notation like:

```pdf:hash://md5/70c3e0fba7379e09e95a38569fe29da7!/p19```

to flip to original page 19 in the document, which would result to showing page 27 of the referenced pdf document with content id ```hash://md5/70c3e0fba7379e09e95a38569fe29da7``` .

suggest to review "PDF17: Specifying consistent page numbering for PDF documents" at https://www.w3.org/TR/WCAG20-TECHS/PDF17.html .

![image](https://github.com/user-attachments/assets/b3b5ffa1-2b4a-44bf-ac56-4d3136460196)

**Comment by myrmoteras** [comment]
Originally, but at the moment not. I understand this not possible so far in Zenodo, but it might become an option again.

**Comment by jhpoelen** [comment]
With preston v0.10.0, you can now address specific pages and page ranges within a pdf with a known content id / digital signature. 

For instance, to select page 1 of digital content associated with:

> Andersen, K.C. 1912. Catalogue of the Chiroptera in the collection of the British Museum. Volume I: Megachiroptera. British Museum (Natural History), British Museum Catalogue, 854 pp. https://www.biodiversitylibrary.org/part/91323 https://doi.org/10.5962/bhl.title.8322 hash://md5/56384a6778e2c67bbd8ebe4d63f770cf

 you can now specify


```pdf:hash://md5/56384a6778e2c67bbd8ebe4d63f770cf!/p1```

and use existing preston functionality (and server addressing) like:


```
preston cat\
 --remote https://linker.bio,https://zenodo.org\
 'pdf:hash://md5/56384a6778e2c67bbd8ebe4d63f770cf!/p1'\
 > some.pdf
```

as well as via server addressing like:

https://linker.bio/pdf:hash://md5/56384a6778e2c67bbd8ebe4d63f770cf!/p1


For a more complex example, see:

https://linker.bio/pdf:hash://md5/56384a6778e2c67bbd8ebe4d63f770cf!/p2-p4,p20-p24

which renders pages 2-4 and 20-24 of digital content with signature hash://md5/56384a6778e2c67bbd8ebe4d63f770cf .

![Screenshot from 2024-11-05 14-34-43](https://github.com/user-attachments/assets/52371ba9-0155-403b-bef1-c9e4f64b4653)
