### ISSUE TITLE
assess impact of RSS reader failing to parse iDigBio RSS feeds

### ISSUE THREAD

**Issue by mielliott** [bio-guoda/preston#36]
It's unclear how https://github.com/bio-guoda/preston/issues/32 affected the monitoring of dataset URLs registered with iDigBio in the combined iDigBio, GBIF, and BioCASe observatory (including https://zenodo.org/record/3484205).

A script could be written which takes provenance for two data networks and identifies URLs that were registered by one network but not the other. Specifically, we are interested in finding out how many URLs supplied by iDigBio were not also supplied by GBIF.

**Comment by jhpoelen** [comment]
We've discussed this issue in various meetings and came to the conclusion that we won't look into the reliability of urls that were registered in both iDigBio and GBIF networks for the time being. For notes, please see https://github.com/bio-linker/organization/wiki .
