### ISSUE TITLE
use quad graph labels to group statements by activity graphs

### ISSUE THREAD

**Issue by mielliott** [bio-guoda/preston#41]
Quadification (made possible by #39; see https://blogs.oracle.com/oraclespatial/modeling-evolving-data-in-graphs%3a-the-power-of-rdf-quads, thanks @jhpoelen) can allow us to reference (groups of) statements in other statements. We can use this to track which activities informed others.

Proposed implementation:
1. The first statement emitted by a named activity should be a declaration of the activity (something like ```activityUUID isA Activity```)
2. The activity declaration and any statements that follow should use the activity name as a temporary graph label (.e.g. ```_:activityUUID```)
3. If a future activity is informed by a statement possessing a graph label, the future activity may identify the activity that produced the statement by referencing the graph label of the statement and emitting ```newActivityUUID wasInformedBy activityUUID```
4. Once an ```activityUUID endedAt timeLiteral``` is seen by an Activity Tracker (new!), the activity's statements should be serialized and hashed, then the ```_:activityUUID``` labels should be replaced by the resulting hash (```hash://sha256/abc...```)
5. On ```preston reprocess```, the ```hash://sha256/abc...``` graph labels should be translated back into the original ```activityUUID``` to allow future activities to reference the activity responsible for an informative statement

@jhpoelen this proposed implementation is how I understood our ideas from https://github.com/bio-linker/organization/wiki/2020-03-06-Work-Session-Notes; please holler if you think I missed or misunderstood anything.

**Comment by jhpoelen** [comment]
I am having second thoughts on the serialization of the activity graphs and usage of content hash at named graph. 

I find myself drawn back to the idea to just say:

```
<subj> <verb> <obj> <activityUUID> .
```
instead of 
```
<subj> <verb> <obj> <_:activityUUID> (temporary)
<subj> <verb> <obj> <hash://sha256/1234> (final)
```

**Comment by mielliott** [comment]
I think using the activity UUID as the named graph is in line with the examples at https://blogs.oracle.com/oraclespatial/modeling-evolving-data-in-graphs%3a-the-power-of-rdf-quads, so I'm fine with it. Also I think it's less confusing.

The second offers more security, for sure (the group of statements under the same activity can be authenticated by recomputing the hash), but maybe it's unnecessary. The whole log is named by its hash, so in that broader scope, we still have the same ability to authenticate statements.

**Comment by jhpoelen** [comment]
I agree that the whole provenance log is still named by its hash.

One thing I wonder is whether the re-use of the activity uuid might cause some semantic confusion. By reusing the activity uuid for an activity describing an activity and a named graph, which one should be chosen when referring to the activity uuid in a subj/obj ? Did you catch anything in the rdf/nquad spec about that?

**Comment by mielliott** [comment]
That actually is addressed in https://www.w3.org/TR/rdf11-concepts/#dfn-graph-name:
> Despite the use of the word “name” in “named graph”, the graph name is not required to denote the graph. It is merely syntactically paired with the graph. RDF does not place any formal restrictions on what resource the graph name may denote, nor on the relationship between that resource and the graph.

So, it's permissible for the "graph name" to also be an identifier for an activity/entity/whatever.

Good point though about not being able to differentiate the activity from the graph associated with the activity.

**Comment by jhpoelen** [comment]
Thanks for looking up the section in the spec. Sounds like we are going for a little code safari - I'd imagine the first stop to be: attach crawl activity uuids to existing quads without changing the functionality. Is this what you had in mind also?
