### ISSUE TITLE
separate unit tests from integration tests

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/preston#45]
Unit tests should not depend on online resources. Integration tests may depend on online resources.

Suggest to using naming convention:

SomeClassNameTest - for unit tests

and

SomeClassNameIT - for integration test

**Comment by jhpoelen** [comment]
fyi @mielliott I've ran Preston tests offline to verify that only *IT tests were failing. If this is not the case on your machine, please re-open and provide details.

**Comment by mielliott** [comment]
@jhpoelen nice! All tests are passing on my machine now.
