### ISSUE TITLE
dataset linking usecase: https://www.gbif.org/dataset/86221faa-f762-11e1-a439-00145eb45e9a

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/preston#47]
via https://twitter.com/dpsSpiders/status/1239610005353123841 - (see attached screenshot) -

dataset titled " Specimen Database of Colorado Vascular Plants " Published by University of Colorado Museum of Natural History  (see https://www.gbif.org/dataset/86221faa-f762-11e1-a439-00145eb45e9a or University of Colorado Museum of Natural History. Specimen Database of Colorado Vascular Plants. Occurrence dataset https://doi.org/10.15468/dsxb4q accessed via GBIF.org on 2020-03-16. and source location https://orphans.gbif.org/US/86221faa-f762-11e1-a439-00145eb45e9a.zip ) was deprecated and replaced by  dataset:

 " University of Colorado Museum of Natural History (2020). University of Colorado Museum of Natural History Herbarium Vascular Plant Collection. Occurrence dataset https://doi.org/10.15468/wyofjv accessed via GBIF.org on 2020-03-16. " available via https://www.gbif.org/dataset/7c5e863f-3f70-4933-b05d-fc57c66dd3f3 with source location https://botanydb.colorado.edu/content/dwca/COLO-V_DwC-A.zip . 

Presumably identifiers were changed in the process. 

![Screenshot from 2020-03-16 16-48-09](https://user-images.githubusercontent.com/1084872/76808990-9af1ee80-67a6-11ea-8ab9-6445827076d1.png)
![Screenshot from 2020-03-16 16-53-42](https://user-images.githubusercontent.com/1084872/76809021-bbba4400-67a6-11ea-8b10-092e70d84aeb.png)
![Screenshot from 2020-03-16 16-53-27](https://user-images.githubusercontent.com/1084872/76809022-bceb7100-67a6-11ea-9741-3a94ecaa7aaf.png)

**Comment by jhpoelen** [comment]
Please note that the now deprecated original dataset at https://orphans.gbif.org/US/86221faa-f762-11e1-a439-00145eb45e9a.zip is no longer served / available via GBIF, but copies are kept in the internet archive via https://archive.org/download/biodiversity-dataset-archives/data.zip/data/30/26/302605ffa81aedd7be5b24c6e994b6f694510ae74d9c8cf34c67faa5e037a554 and elsewhere. See also https://hash-archive.org/history/https://orphans.gbif.org/US/86221faa-f762-11e1-a439-00145eb45e9a.zip .

The new endpoint for original dataset (e.g., https://botanydb.colorado.edu/content/dwca/COLO-V_DwC-A.zip ) was registered very recently and has not yet been picked up by preston observatories. Preliminary results confirm that that content of the deprecated datasets and the newly registered dataset are different as suggested by @dshorthouse . 

@dshorthouse @debpaul - thanks for pointing out this example on twitter - excellent example of how dataset change on the internet and how easy it is to lose track of our valuable datasets.

**Comment by jhpoelen** [comment]
fyi @cboettig

**Comment by jhpoelen** [comment]
See attached GBIF dataset json for deprecated dataset and its replacement:

```bash
$ curl https://api.gbif.org/v1/dataset/86221faa-f762-11e1-a439-00145eb45e9a > 86221faa-f762-11e1-a439-00145eb45e9a.json
$ curl https://api.gbif.org/v1/dataset/7c5e863f-3f70-4933-b05d-fc57c66dd3f3 > 7c5e863f-3f70-4933-b05d-fc57c66dd3f3.json
```

[7c5e863f-3f70-4933-b05d-fc57c66dd3f3.json.txt](https://github.com/bio-guoda/preston/files/4340893/7c5e863f-3f70-4933-b05d-fc57c66dd3f3.json.txt)
[86221faa-f762-11e1-a439-00145eb45e9a.json.txt](https://github.com/bio-guoda/preston/files/4340894/86221faa-f762-11e1-a439-00145eb45e9a.json.txt)

**Comment by dshorthouse** [comment]
All of gbifID, institutionCode, collectionCode, catalogNumber and occurrenceID have changed. As near as I can tell, the reason for the across-the-board changes is that they bought a new barcode sticker machine some time ago and finally got around to serving the new identifiers and deprecating the old identifiers. The "V" am guessing is to now give some local branding to their vascular plants and differentiate the dataset from others they serve.

I have witnessed this deprecation of identifiers because of a new investment in a barcode sticker machine.

Hard to police this behavior when the disruption is baked into the offerings of a deficient vendor.

**Comment by jhpoelen** [comment]
For completeness, I am attaching the deprecated source archive to this issue:

University of Colorado Museum of Natural History. Specimen Database of Colorado Vascular Plants. Occurrence dataset https://doi.org/10.15468/dsxb4q accessed via GBIF.org on 2020-03-16 with content hash://sha256/302605ffa81aedd7be5b24c6e994b6f694510ae74d9c8cf34c67faa5e037a554 

[302605ffa81aedd7be5b24c6e994b6f694510ae74d9c8cf34c67faa5e037a554.zip](https://github.com/bio-guoda/preston/files/4340941/302605ffa81aedd7be5b24c6e994b6f694510ae74d9c8cf34c67faa5e037a554.zip)

**Comment by jhpoelen** [comment]
@dshorthouse thanks for providing the occurrence record example at https://www.gbif.org/occurrence/2573559174 . As far as I can tell, this record is new and did not exist in the deprecated dataset. However, another record that describes an occurrence of _Astragalus leptaleus_ with locale ```North end of South Park, ½ mile west of Jefferson.``` was present in both deprecated and current data archive. 

in deprecated dataset:

$ zipgrep "Astragalus leptaleus" 302605ffa81aedd7be5b24c6e994b6f694510ae74d9c8cf34c67faa5e037a554.zip | grep "North end"
occurrence.txt:125540962											UCMC	COLO			PreservedSpecimen					184530		Richard Walter													1963	7	20												North America				USA		Colorado	Park		North end of South Park, ½ mile west of Jefferson.											Astragalus leptaleus								Plantae				FABACEAE	Astragalus		leptaleus				A. Gray		


and replacement dataset:

$ zipgrep "Astragalus leptaleus" cc4d93805d308e5ef2f4a44b4dc491f993e1d80bf4f15d7823ca7c3364392add.zip | grep "North end"
occurrences.csv:62960,COLO,V,,f5da8b4f-e389-4436-b71d-1c3e0a4baacc,PreservedSpecimen,37926eec-e110-4e33-a5de-c222a00155a4,00320218,184530,Plantae,Magnoliophyta,,Fabales,FABACEAE,"Astragalus leptaleus",3772,"A. Gray",Astragalus,leptaleus,,,,,,,,,,"Richard Walter",775,1963-07-20,1963,7,20,201,,"20 July 1963","Astragalus leptaleus, det. Duane Isely, 1979. Survey of the Vascular Flora of North End of South Park, Michigan Creek Drainage Area near Jefferson, 9,000-10,500 ft. alt.","Frequent in the moist roadside areas.",,,,,,"Flr & Frt",,,,,,,,"United States",Colorado,Park,,"North end of South Park, ½ mile west of Jefferson.",,,,,,,,,,,,2926,,,,,"9600 ft, 2926 m",,,"Access DB","2019-11-04 15:09:20",http://creativecommons.org/licenses/by-nc-sa/3.0/,,,urn:uuid:37926eec-e110-4e33-a5de-c222a00155a4,https://botanydb.colorado.edu:443/collections/individual/index.php?occid=62960

Note that the catalog number ```184530``` and institutionCode ```COLO``` seems to have been left  untouched. 

Acknowledging the reality of evolution of datasets, the challenge is to scale-up/automate this process of relating older datasets to newer ones on both the collection/dataset and individual record.

**Comment by dshorthouse** [comment]
Playing devil's advocate – why do we care about datasets for primary natural history specimen data? Are these merely a by-product of DwC-A files, a technological response to poor performance when paging through large XML documents? Are datasets for primary specimen data adding value or are they merely artificial, convenient wrappers? A dataset for tertiary or derived data makes sense because it's a citable unit, constructed in support of a publication or sets of publications. But primary specimen data are necessarily volatile. If they remained static, I'd question whether or not there's any activity in the collection or if they have the capacity to respond to user requests. I have yet to see a compelling reason for retaining versions for primary specimen data except perhaps to do some digital archaeology and sort out problems.

**Comment by jhpoelen** [comment]
Hey @dshorthouse - thanks for playing devils advocate. I'll take a stab at answering the questions you raise, but before I do, I opened a new issue on this in #49, because it is a bit of a departure from this dataset linking use case. I am planning to capture the rationale there.
