### ISSUE TITLE
suggest to make "preston process" an alias of "preston update"

### ISSUE THREAD

**Issue by mielliott** [bio-guoda/preston#50]
If I understand correctly, @jhpoelen proposed this change to make `process` online and reuse the test cases already in place for `update`.

Currently, `process` receives a string of RDF quads as input, but `update` doesn't have a way to process them. Maybe we could either
a) add an RDF nquads parser to the list of statement processors (bad idea?)
b) instead of making `process` an alias, extend the `CmdUpdate` class and override `initQueue` to parse `System.in` for quads (to preserve current behavior, if this is desired)

**Comment by jhpoelen** [comment]
related to #37 

I much like option b. to get started. 

I am not sure if I understand option a. - how would a processor be notified of new quads streaming in via stdin ?

**Comment by mielliott** [comment]
Right, option a doesn't make sense, haha. I was mixing a couple unrelated ideas in my head. Let's ignore that. Option b it is.

**Comment by jhpoelen** [comment]
decided to keep process and update separate: 

process operates only on the "content-based" universe,

whereas update implements a loco (location -> content) transform (aka fortes transform).
