### ISSUE TITLE
trying to understand the simplified hexastore

### ISSUE THREAD

**Issue by cboettig** [bio-guoda/preston#52]
I'm reading https://github.com/bio-guoda/preston/blob/master/architecture.md#simplified-hexastore for the third time and I think the magic of the hexastore is starting to dawn on me... But I'm still struggling to follow the example.  Partly I'm struggling over the pseudo-code, and figuring out when you're hashing a url and when you're hashing content at the url.  

e.g. what would the following block look like on a bash command line using `sha256sum`?

```
sha256(
  sha256(<https://search.idigbio.org/v2/search/publishers>)
  + sha256(<http://purl.org/pav/hasVersion>)
) 
```

(I think you are hashing urls as strings, but I tried:

```
echo -n "https://search.idigbio.org/v2/search/publishers" | sha256sum
3edfe376ce9a6602fec3a6d3fa30d1d97bbf7a768fb855c8c75eeab389e1e3ef  -
```
which is not the hash shown in the example.  The next one seems to match though:

```
 echo -n "http://purl.org/pav/hasVersion" | sha256sum
0b658d6c9e2f6275fee7c564a229798c56031c020ded04c1040e30d2527f1806  -
```

I'm not entirely sure how to "add" them either (i.e. is that two hashes, written in hash-uri format and separated by a newline?)

apologies for being dense here.

**Comment by jhpoelen** [comment]
@cboettig thanks for opening the issue about the section on the hexastore in the architecture page. I reviewed it and found some errors. I've updated the text. Please review and close this issue if the update are sufficient. If not, I'd welcome your feedback and chip away at it some more.

See https://github.com/bio-guoda/preston/blob/master/architecture.md .

**Comment by cboettig** [comment]
Nice! just read the revised version and it's definitely much easier to follow.  

I just had a few minor questions:

- is the convention of combining hashes by appending with no separator/delimiter, e.g. 

```
echo -n "hash://sha256/1a9158fc90d1b38fe7fa71118daa88861c0d40761e4c1452c64e069c35617271hash://sha256/0b658d6c9e2f6275fee7c564a229798c56031c020ded04c1040e30d2527f1806" | sha256sum
```
a standard practice? 

- In the 'abstract notion of a graph', why no prefix (e.g. `urn:uuid:`) on the graph id?
- The introduction of the arbitrary uid for 'the abstract notion of a graph' is a bit ... abstract?  Could you illustrate this with an example of some other object that also hasVersion but isn't as abstract?

Anyway, I think I now see how to recursively navigate the hexastore, but am still digesting this.  Any other examples or general reading on hexastore you could reference?

**Comment by jhpoelen** [comment]
@cboettig thanks for your comments. 

> Is the convention of combining hashes by appending with no separator/delimiter a standard practice? 

I am not aware of any convention to combine hashes, so I took the path of least resistance. 

> In the 'abstract notion of a graph', why no prefix (e.g. `urn:uuid:`) on the graph id? 

I didn't see any added value to prefixing the uuid. And, a uuid (without prefix) is a valid uri. The main reason for adding the uuid is to have something unique to reference an abstract concept. Sort of like a content hash uri for things that have no content. 

> The introduction of the arbitrary uid for 'the abstract notion of a graph' is a bit ... abstract?  Could you illustrate this with an example of some other object that also prov#hasVersion but isn't as abstract?

An example of a similar abstraction might be [```owl:Thing```](http://www.w3.org/2002/07/owl#) (aka http://www.w3.org/2002/07/owl#Thing , see https://www.w3.org/TR/owl-guide/) . However, I didn't want to commit to owning a domain name (e.g., http://preston.guoda.bio/#biodiversity-graph), so I minted a uuid instead. The abstract uuid is given meaning by the things it relates to. For instance, the  [pav:hasVersion](http://pav-ontology.github.io/pav/index.html#http://purl.org/pav/hasVersion) relationship with a content has uri. Note that the definition of [pav:hasVersion](http://pav-ontology.github.io/pav/index.html#http://purl.org/pav/hasVersion) explicitly allows for abstract resources: ```[...] This property is intended for relating a non-versioned or abstract resource to several versioned resources, e.g. snapshots. [...]```. 

> Any other examples or general reading on hexastore you could reference?  

I added the following reference to the architecture document:

Weiss, C., Karras, P. and Bernstein, A., 2008. Hexastore: sextuple indexing for semantic web data management. Proceedings of the VLDB Endowment, 1(1), pp.1008-1019. Also see https://people.csail.mit.edu/tdanford/6830papers/weiss-hexastore.pdf .

**Comment by cboettig** [comment]
nice, this is great!

**Comment by cboettig** [comment]
pps is there any prior art on doing hexastores with hashes?  From what I understood from Weiss et al piece I have a much better sense of where the "6" comes from in a hexastore, but in less it was supposed to be obvious they didn't really explain doing so with content hashes the way your write-up illustrates so nicely.  If there's no prior art on this, have you considered writing up the hash-based hexastore approach by itself?  

I'm still wrapping my head around the mechanics, but it sounds like it could be a nice alternative to the existing RDF query systems we have available, at least from R without resorting to java plugins (i.e. redland bindings, which scale poorly in performance and lack bulk import of triples).  I think a passable implementation of this is way too big a lift for me though.

**Comment by jhpoelen** [comment]
I haven't seen anyone use a combination of content hash uris, hexastores and "imploded" rdf graphs (i.e., references to content that contain rdf graphs in nquads) approach before. However, I am only selectively reading works on the topic. 

Note that these "imploded" graphs  are a way to avoid a so-called triple explosion when trying to make statements about statements (or groups of statements). I recall reading about this in some rdf spec. 

I wish there was a way to submit a version of a markdown document to some journal or publication platform. This way, the living document can continue to evolve while some version gets a stamp of approval through some editorial/review process.

**Comment by jhpoelen** [comment]
About some R implementation - would it be helpful to have some R code to traverse the history of some Preston archive? Perhaps this would be a pragmatic starting point to figure out whether this (simplified) hexastore idea will stick.

**Comment by jhpoelen** [comment]
from 
from http://www.ninebynine.org/RDFNotes/UsingContextsWithRDF.html#xtocid-63039726

> Using this approach, the number of triples will increase exponentially with the depth of context nesting. I assume that implementations will find ways to encode reification quads in a way that overcomes this problem. Still, RDF/XML with reification quads would be the standard way to exchange such information in a sigle RD graph. Other work (e.g. [18]) has explored different ways to exchange RDF achieving the same effect, typically using a different document to contain the formula in a context.

where [18] is : 

Dan Brickley, Jane Hunter, Carl Lagoze, ABC: A Logical Model for Metadata Interoperability, http://www.ilrt.bris.ac.uk/discovery/harmony/docs/abc/abc_draft.html.
