### ISSUE TITLE
implement a check on creating nquads to make sure that IRIs are up to spec

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/preston#56]
see #55

**Comment by jhpoelen** [comment]
I took some time to see what it would look like to make preston provenance logs comply with the 2005 ```URI``` of https://tools.ietf.org/html/rfc3986 . And, I just reverted a couple of hours of work realizing that adding schemes does not actually improve our ability to create biodiversity dataset graphs.

For instance, I found my self thinking : 

What is the benefit of writing 

```urn:uuid:b8d1b213-81fb-416c-87b1-01ca0dc8f322```

instead of

```b8d1b213-81fb-416c-87b1-01ca0dc8f322```

isn't the latter unique enough? Who's going to bother using and validating that the value with the ```urn:uuid:``` prefix conform to the https://tools.ietf.org/html/rfc4122 ? And, the unix tool  ```uuidgen``` returns ```b8d1b213-81fb-416c-87b1-01ca0dc8f322```, not ```urn:uuid:b8d1b213-81fb-416c-87b1-01ca0dc8f322```. 

Also, API responses from GBIF (see https://github.com/bio-guoda/preston/blob/57e0dd4ee0b089fd0860ba373fdd1c2b87ce6b57/src/test/resources/bio/guoda/preston/process/gbif-dataset-single.json)  and iDigBio (see https://github.com/bio-guoda/preston/blob/57e0dd4ee0b089fd0860ba373fdd1c2b87ce6b57/src/test/resources/bio/guoda/preston/process/idigbio-publishers.json) that include uuids without including the ```urn:uuid``` prefix. 

Another example showing issues with introducing the more strict ```[scheme]:``` URI syntax from a resource obtained from DataONE  https://github.com/bio-guoda/preston/blob/aa2d39662df0e81a88bd84fa89cb9650621ae9f9/src/test/resources/bio/guoda/preston/process/dataone-object-location-list.xml : 

```xml
<ns2:objectLocationList xmlns:ns2="http://ns.dataone.org/service/types/v1">
    <identifier>aekos.org.au/collection/nsw.gov.au/nsw_atlas/vis_flora_module/NOMBIN.20150515</identifier>
    <objectLocation>
        <nodeIdentifier>urn:node:TERN</nodeIdentifier>
        <baseURL>https://dataone.tern.org.au/mn</baseURL>
        <version>v1</version>
        <version>v2</version>
        <url>https://dataone.tern.org.au/mn/v2/object/aekos.org.au%2Fcollection%2Fnsw.gov.au%2Fnsw_atlas%2Fvis_flora_module%2FNOMBIN.20150515</url>
    </objectLocation>
    <objectLocation>
...
```

Here, an identifier ```aekos.org.au/collection/nsw.gov.au/nsw_atlas/vis_flora_module/NOMBIN.20150515``` is used to refer to this dataset. However, the identifier is not a valid 2005 URI and from the context, it is unclear in what kind of base URI might be appropriate to append (e.g., ```https://example.org/aekos.org.au/collection/nsw.gov.au/nsw_atlas/vis_flora_module/NOMBIN.20150515``` ). However, the identifier seems useful to keep around and refer to.

So, some remaining questions are: 

What _value_ does the mandatory 2005 URI scheme actually add?

Would users benefit from applying schemes to these named resources? 

If a perfectly useful custom identifier is used that does not happen to have a scheme, why would we have to invent some scheme just to comply with the 2005 URI spec?  

Isn't the URI scheme adding semantics that should be expressed in quads themselves using "is a" relations? 

Why aren't well-established triple stores like Jena bothered by enforcing 2005 URIs in their IRIs?

What am I missing? 

I probably have to further develop my understanding of the intent and adoption of nquads and their related IRI/URI spec. And that needs a little more time.

@mielliott curious to hear your thoughts.

fyi @cboettig

**Comment by melliott1220** [comment]
I need to chew on this more, @jhpoelen, but I do have some initial "easy" answers.

> What value does the mandatory 2005 URI scheme actually add?

I think, generally, the idea is to make different RDF datasets compatible by enforcing global identifiers, leaving non-skolemized blank nodes as the only possible local identifiers. In the case of UUIDs, if one dataset uses the `urn:uuid` prefix but another doesn't, resolving such discrepancies across datasets might be nontrivial. Although, I get that different identifiers might be used to refer to the same entity (especially across datasets), and identifying those duplicates would raise similar complications.

> Would users benefit from applying schemes to these named resources?

One benefit to users is the ability to use Preston-generated provenance with software that enforces absolute URIs (e.g. https://github.com/RDFLib/rdflib). I acknowledge that the benefit here is not a product of enforcing schemes.

**Comment by jhpoelen** [comment]
Curious to hear your comments @mielliott before I start moving on this.

**Comment by mielliott** [comment]
To preserve the structure provided by the intermediate uuids, we could use blank nodes. The original uuid could be linked to the blank node as a string literal if/when it's useful to preserve it. I don't know what relationship would be used to do that though (below I made up "hadLabel").
```
<hash://sha256/aaaaa> <hadMember> _:b .
_:b <hadLabel> "ac9673fa-73cf-42db-a352-e1848f12e483" .
```
An even crazier (but kinda neat) idea: when an identifier is found inside a resource, append the identifier as a fragment onto the hash URI. Like,
```
<hash://sha256/aaaaa> <hadMember> <hash://sha256/aaaaa#someUUID>
<hash://sha256/aaaaa#someUUID> <hadMember> <http://example.com/dwca>
```
Note that the use of fragment identifiers is non-normative according to https://www.w3.org/TR/rdf11-concepts/#section-fragID. They seem to fit the bill though: "They identify a secondary resource that is usually a part of, view of, defined in, or described in the primary resource." And even though their use is non-normative, their presence is totally compatible with 2005 URIs.

**Comment by mielliott** [comment]
For the record, an example of the structure would be nice to preserve is when DWCA and EML file locations are grouped together under the UUID.

The more I think about using fragments for this purpose, the more I like them. Unless you have any objections or wisdom against using them? @jhpoelen

**Comment by jhpoelen** [comment]
As far as I know, Preston is now generating well-formed IRIs. And, I am starting to appreciate "relaxed" rdf/nquad parsers that have an option to skip malformed rdf/nquads statements.
