### ISSUE TITLE
add option to verify command to include similarity hashes

### ISSUE THREAD

**Issue by mielliott** [bio-guoda/preston#59]

**Comment by jhpoelen** [comment]
@mielliott I took a stab at implementing tlsh and tlsh+tika hashes. 

For now, it look like this:

```
$ cat algae.zip | preston hash -a sha256
hash://sha256/175bdab3638a4fd16d58845a768eba8e76bd01c9cc0f3afc100670d8740214f2
$ cat algae.zip | preston hash -a tlsh
hash://tlsh/423c0388b0e3aff488b022c03d5705ac5dd3dddc6ef199cbd6a661a69569cc85b2d
$ cat algae.zip | preston hash -a tika
hash://tika/574fd07be0a8a2ed5117b2aca254279bbc63a80356d8bf8de935c10f94975374d0c
```

where the algae collection comes from https://github.com/bio-linker/organization/wiki/TLSH-Example .

ltsh - is the hash without the T1xxx prefix, where the T1 is the hash version and xxx encodes file properties. Only the buckets are included 

tika - is a ltsh hash applied after letting tika extract text from the content. 

I've also added the option to the verify command to make it easy to traverse the an entire graph.

**Comment by jhpoelen** [comment]
Please re-open if issues remain.
