### ISSUE TITLE
Use case: verify GBIF DOIs

### ISSUE THREAD

**Issue by faroit** [bio-guoda/preston#62]
Hi, I am new in the community and currently evaluate settings how to create reproducible machine learning datasets based on GBIF queries. Now, I wonder if the following use case could be achieved using preston:

Given DOI generated by GBIF that groups to bundle occurances ([example](https://doi.org/10.15468/dl.4n9w6m))

* can preston use that link directly to download the Darwin Core Archive?
* can preston verify and hash the metadata as well as the images to be downloaded from the different providers?
* do I have to run `update` for this? why?

**Comment by jhpoelen** [comment]
@faroit hey Fabian-Robert - 

Thanks for your message and questions. I much enjoyed learning about your use-case. 

Given the importance of the ability to reliably reference data associated with impressive amount of data GBIF produces, I've decided to prepare an elaborate response, so please bear with me ; )

Currently, GBIF download DOI URLs (or GBIF *query* DOI URLs) like https://doi.org/10.15468/dl.4n9w6m resolve to html pages suited for human consumption. 

So, when running Preston using:

```preston update https://doi.org/10.15468/dl.4n9w6m```, you'd see Preston provenance logging ending with:

```
<https://doi.org/10.15468/dl.4n9w6m> <http://purl.org/pav/hasVersion> <hash://sha256/fe5f69be7ce83b32faeea9a3c275641b1c59dbbce2af57f43ce78d743ebf3e2c> <3ae675f4-e228-47e0-98e9-52a1d784ee15> .
```

Then, look at what the resolved content with content id ```hash://sha256/fe5f69be7ce83b32faeea9a3c275641b1c59dbbce2af57f43ce78d743ebf3e2c``` using:

```
$ preston cat hash://sha256/fe5f69be7ce83b32faeea9a3c275641b1c59dbbce2af57f43ce78d743ebf3e2c | head

<!DOCTYPE html>

<!--[if !IE]> -->
<html lang="en" class="not_ie" ng-app="portal"  >
<!-- <![endif]-->
<!--[if IE]>
<html lang="en" class="ie" ng-app="portal">
<![endif]-->
```
This shows that the queried DOI URL resolves to a (human readable) html page. This page is not designed for programs to ingest and link to related (meta-) datasets. This is perhaps a silly example, but shows that DOIs are typically not designed to help establish reproducible data workflows. 

However, if you'd like, we can think about adding support to Preston and help connect GBIF query DOIs to a download archive that is associated to it by implementing something like:

Step 1. if Preston sees a doi url with that contains "10.15468/" (GBIF's organization DOI registration code), redirect to the associated, machine-readable, GBIF APIs endpoints. In this case, they would be  https://api.gbif.org/v1/occurrence/download/0062961-200221144449610 .

Step 2. resolve content of GBIF api to associated json

```json
{
  "key": "0062961-200221144449610",
  "doi": "10.15468/dl.4n9w6m",
  "license": "http://creativecommons.org/licenses/by-nc/4.0/legalcode",
  "request": {
    "predicate": {
      "type": "equals",
      "key": "TAXON_KEY",
      "value": "4167110"
    },
    "sendNotification": true,
    "format": "DWCA"
  },
  "created": "2020-05-14T08:24:00.109+0000",
  "modified": "2020-05-14T08:24:55.864+0000",
  "eraseAfter": "2020-11-14T08:24:00.044+0000",
  "status": "SUCCEEDED",
  "downloadLink": "http://api.gbif.org/v1/occurrence/download/request/0062961-200221144449610.zip",
  "size": 33353,
  "totalRecords": 39,
  "numberDatasets": 8
}
```

Step 3. Preston recognizes the ```downloadLink``` and resolves dwca URL http://api.gbif.org/v1/occurrence/download/request/0062961-200221144449610.zip . 

Step 4. Preston download the dwca, calculates the content id (or hash) and reports on using:

```
<http://api.gbif.org/v1/occurrence/download/request/0062961-200221144449610.zip> <http://purl.org/pav/hasVersion> <hash://sha256/f0e8a3df97c04c1de91bb610706a2d62e42e4d1d19a0f4e22fe5e20375926d46> <510e6566-8451-4e6f-8881-989efb6dd600> .
```

Step 5. Now, the GBIF download archive can be reliably referenced and resolved using their content id :

```
$ preston cat hash://sha256/f0e8a3df97c04c1de91bb610706a2d62e42e4d1d19a0f4e22fe5e20375926d46 > dwca.zip
$ unzip -l dwca.zip 
Archive:  dwca.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
    44180  2020-05-14 08:24   occurrence.txt
    29876  2020-05-14 08:24   verbatim.txt
     3259  2020-05-14 08:24   multimedia.txt
     1682  2020-05-14 08:24   citations.txt
    15212  2020-05-14 08:24   dataset/821cc27a-e3bb-4bc5-ac34-89ada245069d.xml
     1716  2020-05-14 08:24   dataset/c1aaedc7-b5ba-4baf-9112-ec70637e242e.xml
     4305  2020-05-14 08:24   dataset/040c5662-da76-4782-a48e-cdea1892d14c.xml
     5295  2020-05-14 08:24   dataset/b5cdf794-8fa4-4a85-8b26-755d087bf531.xml
     3157  2020-05-14 08:24   dataset/cd6e21c8-9e8a-493a-8a76-fbf7862069e5.xml
     2167  2020-05-14 08:24   dataset/7adf20e0-c955-11de-95c0-b8a03c50a862.xml
     5748  2020-05-14 08:24   dataset/15f819bd-6612-4447-854b-14d12ee1022d.xml
     3039  2020-05-14 08:24   dataset/bf2a4bf0-5f31-11de-b67e-b8a03c50a862.xml
     1108  2020-05-14 08:24   rights.txt
     3047  2020-05-14 08:24   metadata.xml
    36147  2020-05-14 08:24   meta.xml
---------                     -------
   159938                     15 files
```

With this (minor) added functionality, Preston has (indirectly) associated the GBIF Query DOI with some associated DwC-A archive served by GBIF as some time.

Similar functionality can be added to document image urls and their associated content found in DwC-A.
 
Thanks again for sharing your use case and I am curious to hear your thoughts about the proposed Preston feature(s).

**Comment by jhpoelen** [comment]
Please note that Preston already has functionality to track the source archives associated with GBIF registered datasets. See https://github.com/bio-guoda/preston-amazon/ for an example.

**Comment by jhpoelen** [comment]
@faroit I couldn't resist to implement a first at supporting some of the use case you proposed (see #63 ).

**Comment by jhpoelen** [comment]
#63 provides an example for verifying / tracking content associated with GBIF DOI. 

Please feel free to re-open / comment if there's any additional thoughts on the topic.
