### ISSUE TITLE
allow for tracking GBIF query/download DOIs

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/preston#63]
GBIF issues DOIs for queries that authenticated users submitted to the GBIF platform. These DOIs (also called download or query DOIs) are intended to be used in citations to track usage of GBIF generated biodiversity datasets derived from registered biodiversity datasets.

In #62 , @faroit proposed a use case to use GBIF DOIs to track associated "download datasets" and associated media. 

This issue describes a feature to allow Preston to track GBIF download/query DOI and their associated metadata and (occurrence data) via:

```preston track https://doi.org/10.15468/dl.4n9w6m``` 

or using a synonym command

 ```preston update https://doi.org/10.15468/dl.4n9w6m```

Please note however, that this feature does *not* cover resolving image data. Another issue will be opened for that.

**Comment by jhpoelen** [comment]
I've implemented a first pass at the proposed functionality. Now, when running ```preston track https://doi.org/10.15468/dl.4n9w6m``` or ```preston update https://doi.org/10.15468/dl.4n9w6m``` . Some crucial information is scraped from the GBIF doi landing page hash://sha256/fe5f69be7ce83b32faeea9a3c275641b1c59dbbce2af57f43ce78d743ebf3e2c resolved via https://doi.org/10.15468/dl.4n9w6m :
```
<script>
        var gb = gb || {};
        gb.downloadKey = {
            key: '0062961-200221144449610',
            doi: '10.15468/dl.4n9w6m',
            status: 'SUCCEEDED'
        };
    </script>
``` 
where the "key" was used to generate an api call documented in:

```
<https://api.gbif.org/v1/occurrence/download/0062961-200221144449610> <http://purl.org/pav/hasVersion> <hash://sha256/22c144f6bd31ec392d0f1afcf227943f780c998c8ef766cd8e04940123472595> <4719e927-9418-4e12-b0a2-58a68f79f849> .
```
The resolved content (i.e. hash://sha256/22c144f6bd31ec392d0f1afcf227943f780c998c8ef766cd8e04940123472595) 

```json
{
  "key": "0062961-200221144449610",
  "doi": "10.15468/dl.4n9w6m",
  "license": "http://creativecommons.org/licenses/by-nc/4.0/legalcode",
  "request": {
    "predicate": {
      "type": "equals",
      "key": "TAXON_KEY",
      "value": "4167110"
    },
    "sendNotification": true,
    "format": "DWCA"
  },
  "created": "2020-05-14T08:24:00.109+0000",
  "modified": "2020-05-14T08:24:55.864+0000",
  "eraseAfter": "2020-11-14T08:24:00.044+0000",
  "status": "SUCCEEDED",
  "downloadLink": "http://api.gbif.org/v1/occurrence/download/request/0062961-200221144449610.zip",
  "size": 33353,
  "totalRecords": 39,
  "numberDatasets": 8
}
```

was used to extract and query the downloadLink -  
```
<http://api.gbif.org/v1/occurrence/download/request/0062961-200221144449610.zip> <http://purl.org/pav/hasVersion> <hash://sha256/f0e8a3df97c04c1de91bb610706a2d62e42e4d1d19a0f4e22fe5e20375926d46> <04987f23-6c0b-416b-bd3a-7f08f8b4463c> .
```
With this you can make a relationship between a reliable reference and it's associated doi using:

```
<hash://sha256/22c144f6bd31ec392d0f1afcf227943f780c998c8ef766cd8e04940123472595> <http://www.w3.org/ns/prov#hadMember> <https://doi.org/10.15468/dl.4n9w6m> <9cb3c944-1998-4f04-8e5e-089448f6df20> .
<http://api.gbif.org/v1/occurrence/download/request/0062961-200221144449610.zip> <http://www.w3.org/1999/02/22-rdf-syntax-ns#seeAlso> <https://doi.org/10.15468/dl.4n9w6m> <9cb3c944-1998-4f04-8e5e-089448f6df20> .
```

**Comment by jhpoelen** [comment]
I've attached the related (meta-) data and provenance logs in:

[data.zip](https://github.com/bio-guoda/preston/files/4726223/data.zip)

**Comment by PietrH** [comment]
Using the download service of GBIF that provides DOI's for asynchronous queries would allow us to get around the 100.000 record hard limit for the GBIF occurence search API.

A use case would be building large corpora such as https://doi.org/10.15468/dl.bkc2cj

> Please note however, that this feature does not cover resolving image data. Another issue will be opened for that.

@jhpoelen What issue refers to the image data? It would be a nice use case to be able to pull images directly from either a DOI or hosted DwC-A like https://api.gbif.org/v1/occurrence/download/request/0211271-200613084148143.zip

**Comment by jhpoelen** [comment]
@PietrH Yes, I agree that building a image corpus using the gbif search api would require some creativity to work around the socio-technical limit of 100k result records.

I much like your idea to allow for resolving of images from darwin core archives or even by resolving the download archives (temporarily) associated with GBIF query DOIs. 

Can I suggest to open a separate issue on that new feature (resolve images via dwca)?

 Also, just curious, can you confirm that you are able to use Preston to resolve a (temporarily) associated download archive via it's GBIF query DOI?

**Comment by jhpoelen** [comment]
> Can I suggest to open a separate issue on that new feature (resolve images via dwca)?

I realized that there is already in issue on the image resolving via dwca content at https://github.com/bio-guoda/preston/issues/64 . @PietrH can you please review the issue and make comments when needed? Also, I am open to ideas on how to best implement the image resolving feature, or even accept pull requests. . .

**Comment by faroit** [comment]
@jhpoelen @PietrH we are actively developing [a GBIF media downloader](https://github.com/plantnet/gbif-dl) that directly takes api queries or dwca id/urls. 

I was not aware of a 100k result limitation so this could indeed be a problem for us as well.
@jhpoelen we want to include preston in the tools soon - sorry for not being active on #62 - will come back to this.

**Comment by faroit** [comment]
@PietrH do you have a reference for the hard limitation on GBIF?

**Comment by jhpoelen** [comment]
@faroit thanks for chiming in. Great to hear that you are also working to make more use of the wealth of biodiversity (media) data that have been digitized over the last decades.

I had a brief look at your tool. Look great! Lots of optimizations with parallel retrieval. I was wondering, once your compile a media corpus, how would you cite this in a scientific publication? Also, how would a reader be able to reliably retrieve and verify the compiled media corpus?

**Comment by faroit** [comment]
@PietrH thanks for the pointer, i remember that I read about that limitation but then forgot

**Comment by jhpoelen** [comment]
This thread provided an example of how Preston can be used to track content related to GBIF query/download DOIs.

Please feel free to re-open / comment if there's any additional concerns / thoughts.
