### ISSUE TITLE
implement a range search for similarity hashes

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/preston#66]
the distance between tlsh hashes can be calculated using established methods. 

Deliver a method to identify hashes within a certain distance from a specified hash. 

So, given Hash A, list all the hashes for which | A - B | < C , where B is another hash and C is a distance metric.

**Comment by mielliott** [comment]
See https://github.com/bio-guoda/preston/commit/07ec0b8947b5b36a9e9dac708c3b5d9d8e35c078

I added `TlshTokenizerTest` (in the `search-indexing` branch), which includes a tokenizer that translates a TLSH hash string (not including the "hash://tika-tlsh/" part) into a stream of tokens usable by Lucene. The tests include building the index and querying for similar TLSH strings.

The tokenizer breaks each hexadecimal character in the TLSH string into two 2-bit bins and keeps track of the position of each bin. So, a 1-character string "7" (0111 binary) would be tokenized into two terms, "01 @ position 0" and "11 @ position 1". In the implementation, the bin position and bin value are packed into a single integer.

So, the hex string `deadbeef` is tokenized into `3 5 11 14 18 22 27 29 34 39 43 46 51 54 59 63`. When this string is used as a Lucene query, it's interpreted as "find indexed tlsh hashes containing terms 3 or 5 or 11 or ... or 63" and any hits (indexed tlsh hashes that share at least one of those terms) are scored according to the number of shared terms.

@jhpoelen

**Comment by jhpoelen** [comment]
@mielliott thanks for sharing your implementation prototype of a method to use Lucene to index tlsh hashes to find similar tlsh hashes. I can see how the indexing would work. 

Some open questions:

1. how do you imagine the index process to work? In other words, what is the workflow to create an index from a given provenance log with tlsh hashes and how would you record this process and it's resulting index?
2. how do you imagine to describe the similarities between tlsh hashes and connect these to a specific the search index used to calculate them?
3. how many tlsh hashes can be indexed per second? 
4. how does the resulting lucene index scale with the number of tlsh hashes indexed? 
5. how do you imagine defining and recording a threshold for tlsh distance/similarity?

**Comment by mielliott** [comment]
I've added a `SimilarityIndexTikaTLSH` class in the `search-indexing` branch. It's intended to be used by a processor to incrementally index SHA256-TikaTLSH pairs and find similar contents. It exposes two functions:
https://github.com/bio-guoda/preston/blob/a44291b34f4ad0647a01622b982f18f9952e22b1/src/main/java/bio/guoda/preston/index/SimilarityIndexTikaTLSH.java#L85
https://github.com/bio-guoda/preston/blob/a44291b34f4ad0647a01622b982f18f9952e22b1/src/main/java/bio/guoda/preston/index/SimilarityIndexTikaTLSH.java#L61

Here's a simple processor using those functions:
https://github.com/bio-guoda/preston/blob/f8b34a894bbffc6646d590069767c9eb82ad0fe1/src/main/java/bio/guoda/preston/process/SimilarContentFinder.java#L10-L37

Still need to emit statements (as discussed in #67) and add a Preston command to run a similar-content-finding processor.

Also, I still need to use the TLSH scoring algorithm when searching the index. For now, it's using `BM25Similarity`.

**Comment by jhpoelen** [comment]
Thanks for sharing an initial implementation on the branch and working towards addressing question 1 (e.g., how does the indexing work?). I am curious to learn more about what happens when you run this method again real data at scale after merging this into main.

**Comment by jhpoelen** [comment]
Similarity hashes are useful and for sake of simplicity, temporarily no longer support by Preston.
