### ISSUE TITLE
add method to create a location of all urls in tracked content

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/preston#72]
in working towards paper no. 2, we'd like to have a way to reference a specific part of an existing dataset.

For instance, in case of #71, we'd like to make a list of all urls and their locations that exist in a tracked datasets. 

Example:

```
$ preston ls | preston select-urls 
 . . . process description . . . 
<url A> <located at> <zip:hash://sha256/abcd123!/occurrence.txt#L2>  <--- reference of text file in zip file 
<url B> <located at> <hash://sha256/abcd123#L22> <--- text file

<activity uuid> <generated . . . > . . .
```

**Comment by mielliott** [comment]
@jhpoelen 
> https://github.com/bio-guoda/preston/issues/79#issuecomment-696990120 @mielliott Nice! Oef, I find these text encodings are tricky. btw - I'd much like to start using your URL finder for digging up image urls. Can you add usage example in the use case section of the readme?

I'm working on making a command to use the URL finder, but it's not quite finished yet. My current idea is to do something like
```
preston ls | preston match [your-regex-here]
```
or, if you're looking for URLs,
```
preston ls | preston match --pattern=url
```
or something along those lines. Or we could make an alias of `preston match` (or whatever the command ends up being called) specifically for URLs,
```
preston ls | preston find-urls
```
I'm busy at the moment, but I will try to finish it up later tonight (and post that usage example to the readme). In the meantime, feel free to holler if you have any ideas/concerns about the command syntax. Thanks!

**Comment by mielliott** [comment]
@jhpoelen There's now a working `preston match` command (I haven't created a new release though). See https://github.com/bio-guoda/preston#finding-text-in-tracked-contents.

Note that `preston match`'s output is saved as a new entry in the provenance history, just like `preston tika` and `preston similar`.

**Comment by mielliott** [comment]
It may be useful to allow `preston match` to output the locations of regex groups as well as full regex matches. For example (thinking about #86),

Without groups:
```
$ preston match [regex without groups]
<cut:hash://blahblah!/b15-63> <is> "http://arctos.database.museum/guid/DMNS:Para:784"
<cut:hash://blubblub!/b115-173> <is> "http://arctos.database.museum/guid/DMNS:Para:784?seid=4324"
```

With groups:
```
$ preston match [regex with groups]
<cut:hash://blahblah!/b15-73> <is> "http://arctos.database.museum/guid/DMNS:Para:784"
<cut:hash://blubblub!/b115-173> <is> "http://arctos.database.museum/guid/DMNS:Para:784?seid=4324"
<cut:hash://blahblah!/b60-73> <is> "DMNS:Para:784"
<cut:hash://blubblub!/b115-128> <is> "DMNS:Para:784"
```

Sure, we could also do something like `preston match "letters:letters:numbers", but there might be cases where we want to look for some context around the text we're searching for. In the above example, maybe we only want to find text with the prefix "http://arctos.database.museum/guid/" or "http://another.museum/". Or maybe we'd want to match a full specimen record (e.g. match whole lines in an occurrence.tsv) and at the same time extract some pieces of information from it (e.g. columns 2 and 3).

To make it even more fun, the matched groups could be linked to the full match. Something along the lines of
```
<cut:hash://blahblah!/b15-73> <is> "http://arctos.database.museum/guid/DMNS:Para:784"
<cut:hash://blahblah!/b60-73> <is> "DMNS:Para:784"
<cut:hash://blahblah!/b60-73> <foundIn> <cut:hash://blahblah!/b15-73>
```

Just some thoughts.

**Comment by mielliott** [comment]
`preston match` now reports group matches. If I search through a file containing the text
```text
the duck is in the pond
```
and run `preston match` using the regex
```regex
"the (?<what>\\S+) is in the (?<where>\\S+)"
```
it should output
```
<cut:hash://sha256/blub!/b1-23> <http://www.w3.org/ns/prov#value> "the duck is in the pond" ."
<cut:hash://sha256/blub!/b5-8> <http://www.w3.org/ns/prov#value> "duck" ."
<cut:hash://sha256/blub!/b1-23> <http://www.w3.org/ns/prov#hadMember> <cut:hash://sha256/blub!/b5-8> ."
<cut:hash://sha256/blub!/b20-23> <http://www.w3.org/ns/prov#value> "pond" ."
<cut:hash://sha256/blub!/b1-23> <http://www.w3.org/ns/prov#hadMember> <cut:hash://sha256/blub!/b20-23> ."
```

Note that, to prevent `preston match` from reporting matches for groups we don't care about, they need to be designated as non-capturing groups, e.g. `(?>dontreportme)` instead of `(doreportme)`. Not sure if this is desirable behavior.

Also, a fun extension would be to have preston link each reported group match with the name of the group (if specified). In the above regex
```regex
"the (?<what>\\S+) is in the (?<where>\\S+)"
```
we could associate "duck" with the `<what>` group and "pond" with the `<where>` group. This would allow the user to include some unique semantics in the output to make it easier to work with.

**Comment by jhpoelen** [comment]
I tried it and was able to reproduce your example. 

Very neat!
