### ISSUE TITLE
README - "Quickstart" instructions front and center?

### ISSUE THREAD

**Issue by mjy** [bio-guoda/preston#77]
```
When I am a developer
  and I have independently decided to try PRESTON
   and I come to the README
     then I want to see Quickstart instructions for installing PRESTON 
       at the very top of the README
```

**Comment by jhpoelen** [comment]
hey @mjy thanks for your feedback. I took some time to add quickstart instructions to the Preston readme at https://github.com/bio-guoda/preston#quickstart .

Please review and close this issue when the updates are as desired. If not, please suggest additional improvement.

**Comment by jhpoelen** [comment]
Quickstart was added. Please re-open if you have additional comments / concerns.
