### ISSUE TITLE
One off instructions making a new binary executable should come with a security warning?

### ISSUE THREAD

**Issue by mjy** [bio-guoda/preston#78]
```
As a developer,
   when I see instructions for single line installation
      then I am very happy
    when I see that it adds a binary to my bin
      and changes its permissions
     then I raise my eyebrows
```

**Comment by jhpoelen** [comment]
@mjy thanks!

I've added the warning note to the single line install script: 

":warning: Note that this installs preston using sudo privileges and makes preston.jar executable. Please inspect the script before running it."

Please close this issue if this addressed your concern. If not, please suggest improvements.

**Comment by jhpoelen** [comment]
Changes made. Please re-open if issue was not addressed.
