### ISSUE TITLE
DerefProgressLoggerTest failed on windows ci

### ISSUE THREAD

**Issue by mielliott** [bio-guoda/preston#79]
After no apparent changes to the relevant code, `DerefProgressLoggerTest.logSomethingLong` failed on windows ci:
https://github.com/bio-guoda/preston/runs/1146603171?check_suite_focus=true#step:5:2955

```
[ERROR]   DerefProgressLoggerTest.logSomethingLong:60 
Expected: is "[https://example.org/very...ooooooooooooooooooooong] 1.0% of 1 kB at ? MB/s ETA: < 1 minute"
     but: was "[https://example.org/very...ooooooooooooooooooooong] 1.0% of 1 kB at 0.00 MB/s ETA: < 1 minute"
```

Note the difference: expected "...? MB/s..." but was "...0.00 MB/s..."

Other tests are failing as well, but they shouldn't have any impact on `DerefProgressLoggerTest`.

**Comment by jhpoelen** [comment]
@mielliott this is a test error: the tests likely runs slower/faster for some reason, causing the download timer to be initiated. Suggest to test that the prefix is abbreviated using a startsWith assertion.

**Comment by mielliott** [comment]
Made change as suggested and the issue seems to be fixed.

**Comment by jhpoelen** [comment]
@mielliott Nice! Oef, I find these text encodings are tricky. btw - I'd much like to start using your URL finder for digging up image urls. Can you add usage example in the use case section of the readme?
