### ISSUE TITLE
use case: build image corpus for Herbarium Martii label detection algorithm

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/preston#80]
by @qgroom 

search all herbaria in the world that contain images with a specific kind of label created by ```Herbarium Martii```  

example image:
https://www.botanicalcollections.be/specimen/BR0000014225291

In other words, identify Martii specimen by the kind of label they use.

![Screenshot from 2020-09-22 11-27-25](https://user-images.githubusercontent.com/1084872/93922409-b6decb80-fcc6-11ea-8053-1a34353d1db8.png)

**Comment by jhpoelen** [comment]
One idea is to use all plant specimen images indexed by GBIF, then use an algorithm to detect the label.

**Comment by jhpoelen** [comment]
A by product of this use-case would be a corpus of all plant images in GBIF.

**Comment by jhpoelen** [comment]
@qgroom - please let me know if I captured the use case properly and if you have additional comments / thoughts.

**Comment by qgroom** [comment]
Carl Friedrich Philipp von Martius (1794-1868) was a famous botanist and collector of herbarium specimens in the nineteenth century (https://en.wikipedia.org/wiki/Carl_Friedrich_Philipp_von_Martius). His Brazilian collections are hugely important and contain many types.

Finding all of his specimens would be useful, but having a corpus of images from numerous herbaria opens up the possibility for a wide variety of queries on images, searching for text elements, signatures, stamps, labels, not to mention characters of the plant itself.
