### ISSUE TITLE
add support for "preston cat cut:hash://sha256/0...!/b926-1004"

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/preston#82]
To easy inspect content from recently supported zip/cut prefixes, suggest to add support for commands like:

```
preston cat cut:hash://sha256/052c70c60e7c17123a1bdf18d2ce607cee1b0d96157b6174aae08a2f2f8d53d8!/b926-1004
```

or 
```
preston cat cut:zip:hash://sha256/123a..!/somefile.txt!/b926-1004
```

**Comment by jhpoelen** [comment]
I gotta say that I was pretty excited when I got the following result:  

```
$ preston cat hash://sha256/052c70c60e7c17123a1bdf18d2ce607cee1b0d96157b6174aae08a2f2f8d53d8 | cut -b926-1004
http://www.freshwaterbiodiversity.eu/metadb/bf_mdb_view.php?entryID&#61;BFE_105
```

@mielliott nice work in enabling re-use of unix tool "cut" !

**Comment by jhpoelen** [comment]
btw - perhaps this feature would help make it easier to stream content out of zip files. I tried the ```unzip -p - references.txt``` to stream content from a zip file using ```unzip```, but for some reason, that did not work for me. I expect we'll need this streaming feature to future work. @mielliott curious to hear your thoughts on this.

**Comment by mielliott** [comment]
> btw - perhaps this feature would help make it easier to stream content out of zip files. I tried the `unzip -p - references.txt` to stream content from a zip file using `unzip`, but for some reason, that did not work for me. I expect we'll need this streaming feature to future work. @mielliott curious to hear your thoughts on this.

Are you suggesting to allow more user-friendly syntax than `preston get zip:hash://blahblah!/references.txt`? Something like `preston get hash://blahblah --unzip references.txt`

**Comment by mielliott** [comment]
`preston match` does not currently report decompression steps. If `hash://blahblah` is a compressed file, it will be decompressed and any text matches will be reported as `cut:hash://blahblah!/b12-34`, meaning that bytes 12-34 refer to bytes in the decompressed content. Then, if we do `preston get cut:hash://blahblah!/b12-34`, we would need detect that the content is compressed and automatically decompress it. This doesn't seem horrible, since I don't know why you would ever want to get specific bytes from a compressed file.

I don't think the term "zip" is reserved exclusively for archives (e.g. bzip2 is just compression, not archival). I wonder if something like `cut:zip:hash://blahblah!/!/b12-34` (using `zip:` with no file name after `!/`) would be acceptable?

**Comment by mielliott** [comment]
Also, if we don't mention the decompression, then we lose compatibility with `cut`.

Still, I think I prefer leaving the decompression step implicit... though I might change my mind on this.

**Comment by jhpoelen** [comment]
thanks for comments. 

Making compression explicit would add some useful info, and is in line with a vfs project that inspired this notation. https://commons.apache.org/proper/commons-vfs/filesystems.html -

```
Provides read-only access to the contents of gzip and bzip2 files.

URI Format
gz:// compressed-file-uri
bz2:// compressed-file-uri

Where compressed-file-uri refers to a file of any supported type. There is no need to add a ! part to the URI if you read the content of the file you always will get the uncompressed version.

Examples
    gz:/my/gz/file.gz
``` 

do you'd have:

```cut:bz2:hash://sha256/abc123...!/b123-456```

which is the same as saying

```cut:bz2:hash://sha256/abc123...!/!/b123-456```

**Comment by jhpoelen** [comment]
with this, you can support:

preston cat cut:bz2:hash://sha256/abc123...!/b123-456

as well as 

preston cat hash://sha256/abc123... | bunzip2 | cut -z -b123-456

**Comment by jhpoelen** [comment]
Curious to hear your thoughts on this.

**Comment by jhpoelen** [comment]
Note that zip, unlike tar, combines compression and archive.

**Comment by mielliott** [comment]
> Making compression explicit would add some useful info, and is in line with a vfs project that inspired this notation.

Nice! Good to see that someone else has already decided on how to do this. Let's make 'em explicit.

> Note that zip, unlike tar, combines compression and archive.

Right, I've been wondering if we should use the name of the archive format. Right now, all archive formats are reported as `zip:`. If we're making decompression explicit, then I think it makes more sense now to be more precise, e.g. `gz:tar:`.

**Comment by jhpoelen** [comment]
Ah, I see, I didn't realize that tar's were also reported at ```zip```. 

I'd prefer more explicit as you suggested. Note that this is also consistent with VFS prefixes:

```
Provides read-only access to the contents of Zip, Jar and Tar files.

URI Format

zip:// arch-file-uri[! absolute-path]

jar:// arch-file-uri[! absolute-path]

tar:// arch-file-uri[! absolute-path]

tgz:// arch-file-uri[! absolute-path]

tbz2:// arch-file-uri[! absolute-path]

Where arch-file-uri refers to a file of any supported type, including other zip files. Note: if you would like to use the ! as normal character it must be escaped using %21.
tgz and tbz2 are convenience for tar:gz and tar:bz2.

Examples

    jar:../lib/classes.jar!/META-INF/manifest.mf
    zip:http://somehost/downloads/somefile.zip
    jar:zip:outer.zip!/nested.jar!/somedir
    jar:zip:outer.zip!/nested.jar!/some%21dir
    tar:gz:http://anyhost/dir/mytar.tar.gz!/mytar.tar!/path/in/tar/README.txt
    tgz:file://anyhost/dir/mytar.tgz!/somepath/somefile
```

**Comment by mielliott** [comment]
The correct archive type should now be reported, but I should make some tests to make sure it works for types other than .zip. Compression type still needs to be made explicit.

**Comment by jhpoelen** [comment]
I was able to use:

```
$ preston cat --remote https://deeplinker.bio 'zip:hash://sha256/d762847b58b14f1ebe305698d109b231b346fff714f9ca4189da2f4ee00fec85!/eml.xml'
[https://deeplinker.bio/d...4f9ca4189da2f4ee00fec85] 100.0% of 169 kB at 0.32 MB/s completed in < 1 minute
<eml:eml xmlns:eml="eml://ecoinformatics.org/eml-2.1.1"
         xmlns:dc="http://purl.org/dc/terms/"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="eml://ecoinformatics.org/eml-2.1.1 http://rs.gbif.org/sche
```

Thanks for adding this neat feature @mielliott !
