### ISSUE TITLE
Incomplete text matches at textmatcher buffer boundaries

### ISSUE THREAD

**Issue by mielliott** [bio-guoda/preston#84]
`preston match` uses a (currently 4KB) buffer when searching for text matches. When a match crosses the buffer boundary, if the substring from the start of the match up to the buffer boundary is a valid match, it gets reported as a match. Correct behavior would be to not report that match, and instead refill the buffer and continue searching until the true end of the match is found.

```
$ echo "<http://ipt.vertnet.org:8080/ipt/archive.do?r=dmn> <http://purl.org/pav/hasVersion> <hash://sha256/d762847b58b14f1ebe305698d109b231b346fff714f9ca4189da2f4ee00fec85> ." | preston match
...
<cut:zip:hash://sha256/314575f66a10953a3cc5c6c8db4df74c593a878090f2387ee02fbcdd85ebcd2f!/multimedia.txt!/b472408-472415> <http://www.w3.org/ns/prov#value> "http://a" <4a5ffdb6-61ff-46a2-9b3a-80665f965799> .
...
```
The reported location for the match is correct:
```
preston get hash://sha256/314575f66a10953a3cc5c6c8db4df74c593a878090f2387ee02fbcdd85ebcd2f > content
$ unzip -p content multimedia.txt | cut -z -b472408-472456
http://a
```
But extending the byte range proves that the match is incomplete:
```
$ unzip -p content multimedia.txt | cut -z -b472408-472456
http://arctos.database.museum/media/10604282?open
```

**Comment by mielliott** [comment]
The automated tests seem to like the fix. Closing.

**Comment by jhpoelen** [comment]
Nice catch! Thanks for fixing it . . .  

Is it correct that when you said:

```
preston get hash://sha256/314575f66a10953a3cc5c6c8db4df74c593a878090f2387ee02fbcdd85ebcd2f > content
$ unzip -p content multimedia.txt | cut -z -b472408-472456
http://a
```

you meant to say:

```
preston get hash://sha256/314575f66a10953a3cc5c6c8db4df74c593a878090f2387ee02fbcdd85ebcd2f > content
$ unzip -p content multimedia.txt | cut -z -b472408-472415
http://a
``` 

?

**Comment by mielliott** [comment]
True! Looks like I got a little carried away when copying and pasting. I edited the post to show the correct byte range. Thanks.
