### ISSUE TITLE
create prototype for a link registry service

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/preston#93]
Create a service that accepts streams from https://github.com/bio-guoda/preston-pattern-registry 

and enable the request of these streams using a microservice. 

This is to enable client to listen in on the datasets that contain values that match specific pattern.

This would answer the question:

List all datasets that contain values that match pattern ```[any regex pattern]```

**Comment by jhpoelen** [comment]
hey @mielliott - I created a kafka install on preston server using steps documented at https://github.com/bio-guoda/preston-scripts/tree/master/server . This includes examples of creating a topic and sending/receiving messages.

**Comment by mielliott** [comment]
Thanks for making this @jhpoelen! I'll check it out.

**Comment by jhpoelen** [comment]
we've established that preston can be used as a basis for web services.
