### ISSUE TITLE
create webservice prototype to retrieve eml.xml for any content hash

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/preston#94]
```curl "....zip:hash://sha256/....!/eml.xml" > eml.xml```

**Comment by jhpoelen** [comment]
hint: 

configure nginx to execute a preston instance and stream the results as part of the response.

**Comment by mielliott** [comment]
@jhpoelen here's a first go of it:

I used the nifty socat tool to create a web interface for preston:
```
socat TCP4-LISTEN:8080,reuseaddr,fork SYSTEM:"./preston-web-service.sh" 
```
socat pipes incoming HTTP requests to https://github.com/bio-guoda/preston-scripts/blob/main/preston-web-service.sh, who looks at the request URI and decides what preston needs to do for us, then runs the appropriate Preston command and pipes his output back to whoever issued the HTTP request.

I then told nginx to redirect requests to the socat server:
```
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    merge_slashes off; # this stops "hash://" from being interpreted as "hash:/"
    location ~ "/(get|cat)/(.*)" {
        proxy_pass http://127.0.0.1:8080/$1/$2;
    }
}
```

and then used cURL to ask Preston for stuff:
```
$ curl 'localhost/cat/zip:hash://sha256/314575f66a10953a3cc5c6c8db4df74c593a878090f2387ee02fbcdd85ebcd2f!/eml.xml'
<eml:eml xmlns:eml="eml://ecoinformatics.org/eml-2.1.1"
         xmlns:dc="http://purl.org/dc/terms/"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="eml://ecoinformatics.org/eml-2.1.1 http://rs.gbif.org/schema/eml-gbif-profile/1.1/eml.xsd"
         packageId="5f3463d2-51b6-4a8a-b252-9bab4388934e/v34.39" system="http://gbif.org" scope="system"
         xml:lang="eng">
...
```
and Preston delivers.

Note that I only configured nginx to forward get/cat commands. Any command can be curled to the socat port directly (if accessible), e.g.
```
$ curl 'localhost:8080/version
```

I've only tested this on my own local machine, so it isn't yet deployed on preston.guoda.bio.

**Comment by mielliott** [comment]
Also, I'm not sure yet how to go about returning error codes. Since we're streaming things, the HTTP header gets streamed out before preston even starts doing its job, so I'm not sure the best way to see if preston complains or not (e.g. if a `hash://blah` can't be resolved, or if a `cut:zip:hash://blah!/yadda` is malformed) before setting the status code. As far as I can tell, I can't get an exit status from Preston until it finishes executing. Right now, I just always return 200 OK, but maybe we sometimes want to return a 404/etc.

**Comment by jhpoelen** [comment]
Cool to see that you used socat + nginx + preston . How modular! 

Perhaps the acis informatics folks have some ideas on how to manage the return codes. 

Am looking forward to getting this up and running publicly. If you feel comfortable, you can apply the changes on the server. If not, I'd be happy to help you through the process.

So now we'll just have to build a lightweight web api on top of Kafka right?

Hoping to give your socat/nginx/preston trifecta a try tomorrow!

**Comment by mielliott** [comment]
> Perhaps the acis informatics folks have some ideas on how to manage the return codes.

Maybe, I can check with them.

> Am looking forward to getting this up and running publicly.

Check it out!

https://preston.guoda.bio/version

https://preston.guoda.bio/cat/zip:hash://sha256/314575f66a10953a3cc5c6c8db4df74c593a878090f2387ee02fbcdd85ebcd2f!/eml.xml

https://preston.guoda.bio/cat/cut:zip:hash://sha256/314575f66a10953a3cc5c6c8db4df74c593a878090f2387ee02fbcdd85ebcd2f!/eml.xml!/b822-844

> So now we'll just have to build a lightweight web api on top of Kafka right?

Sounds about right!

> Hoping to give your socat/nginx/preston trifecta a try tomorrow!

Exciting!

**Comment by jhpoelen** [comment]
This is beyond cool!

```
$ curl --silent 'https://preston.guoda.bio/cat/cut:zip:hash://sha256/314575f66a10953a3cc5c6c8db4df74c593a878090f2387ee02fbcdd85ebcd2f!/eml.xml' | head 
<eml:eml xmlns:eml="eml://ecoinformatics.org/eml-2.1.1"
         xmlns:dc="http://purl.org/dc/terms/"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="eml://ecoinformatics.org/eml-2.1.1 http://rs.gbif.org/schema/eml-gbif-profile/1.1/eml.xsd"
         packageId="5f3463d2-51b6-4a8a-b252-9bab4388934e/v34.39" system="http://gbif.org" scope="system"
         xml:lang="eng">

<dataset>
  <alternateIdentifier>5f3463d2-51b6-4a8a-b252-9bab4388934e</alternateIdentifier>
  <alternateIdentifier>http://ipt.vertnet.org:8080/ipt/resource?r=dmns_mamm</alternateIdentifier>
```

You just created a bridge between our comfortable old creaky shakey location-based world and the cryptographical content-based world!

I need some time to let this sink in. Hoping to put the preston nginx config under version control, so that you can easily install it. How do you think we can best document this?

-jorrit
