### ISSUE TITLE
move service configuration into preston-service repository

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/preston#95]
we now have various scrripts / configuration etc

this will live in 

/var/lib/preston/ 

and has directories like:

systemd/system/
kafka/config 
zookeeper/config

**Comment by mielliott** [comment]
@jhpoelen I've committed to the files to the preston-service repo. Note that the scripts and configs that are currently deployed are still in place, and some committed files still use absolute paths (e.g. /home/mielliott/...) that need to be changed.

**Comment by jhpoelen** [comment]
@mielliott thanks - I'll take a stab at implementing changes as discussed.

**Comment by jhpoelen** [comment]
I've added remaining config and deployed to server. @mielliott please re-open issue if you have some comments: happy to hear feedback.
